### ISSUE TITLE
App opens in a weird state

### ISSUE THREAD

**Issue by jbrennan** [insidegui/WWDC#1]
Yosemite 10.10.2

![screen shot 2015-04-21 at 10 46 08 am](https://cloud.githubusercontent.com/assets/131923/7258815/b0c5822a-e813-11e4-97dd-5a5ffeae3a70.png)

**Comment by insidegui** [comment]
Interesting... must have something to do with autolayout. What's your screen resolution?

**Comment by jbrennan** [comment]
1440x900 (retina display). I was able to fix it by going fullscreen and then adjusting the splitview (the splitview seemed stuck when it first opened). After returning from fullscreen, I was able to adjust it willy nilly.

**Comment by jbrennan** [comment]
Oh, and this was the build I downloaded, I didn’t build it myself.

**Comment by insidegui** [comment]
Can you test [this new build](http://cl.ly/2w0s2B080t0j/br.com.guilhermerambo.WWDC.savedState.zip) to see if it fixes the problem?

Before launching It make sure to delete the folder **~/Library/Saved Application State/br.com.guilhermerambo.WWDC.savedState**

**Comment by jbrennan** [comment]
Hmm you seem to have linked to your own version of the application state, not a new build?

**Comment by insidegui** [comment]
Uoops, wrong key combination :P

There you go: http://cl.ly/3y3t013D3M20/WWDC.app.zip

**Comment by jbrennan** [comment]
Much better, thanks!:

![screen shot 2015-04-21 at 11 46 06 am](https://cloud.githubusercontent.com/assets/131923/7260022/03b905ee-e81c-11e4-8515-451257606608.png)
