### ISSUE TITLE
Should the app be localized?

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#106]
Since all of WWDC's content is in english, I don't think there is much to gain by localizing the app. But I would like to hear other opinions and arguments.

Go ahead :)

Edit: if you think the app SHOULD be localized, please explain why.

**Comment by Frizlab** [comment]
Even though I’m French, I personally don’t care about localization of this product (which, by the way, I find awesome :wink:).

**Comment by wang9262** [comment]
It will be great to integrate the chinese subtitles just as the Safari does.By the way, the Safari screen shot is as below
![qq20160312-1 2x](https://cloud.githubusercontent.com/assets/5634225/13721297/ba82bb44-e85c-11e5-8b3e-a13557959d66.png)

**Comment by insidegui** [comment]
Hi @wang9262 ! You can already use the chinese subtitles in the app:

![subs](https://cloud.githubusercontent.com/assets/67184/13722757/68831cf4-e82e-11e5-946e-20a336d69e6e.png)

**Comment by wang9262** [comment]
yeah,I got it.But when I select the HD Video,there is no Chinese subtitle option.Is the Chinese subtitle is not in the HD streaming m3u8 files?

**Comment by insidegui** [comment]
Probably. The `Watch in HD` option uses the download link for the HD video. But the streaming video (`Watch Video` option) will be in HD as long as your connection can keep up.

**Comment by wang9262** [comment]
Great,thanks for your reply. :+1:
