### ISSUE TITLE
Error trying to AirPlay

### ISSUE THREAD

**Issue by tracicot** [insidegui/WWDC#108]
Whenever I try to cast the stream via AirPlay, I get "An error occurred loading this content." Loading the video on Apple.com works fine. Anyone else experiencing this?

**Comment by insidegui** [comment]
I will test this and see if it happens to me. What version of OS X and what Apple TV are you using?

**Comment by tracicot** [comment]
Actually, this is a false alarm. I was trying to watch What's New in Cocoa from 2014, which failed to cast. I accidentally loaded up What's New in Cocoa from 2015 on Apple, which works both in WWDC and on the web. I think the 2014 video itself is bad, as it doesn't cast from Apple's site either.

**Comment by insidegui** [comment]
Ok then, I will have a look anyway because this is an area I haven't tested very much...
