### ISSUE TITLE
Support filtering for missing items

### ISSUE THREAD

**Issue by lmihalkovic** [insidegui/WWDC#110]
Currently 'favorites' and 'downloaded' only filter on the true case. This issue is for people who like me would like to see what is not stored locally.

Default is to display all items:
<img width="469" alt="screen shot 2016-02-17 at 6 49 22 pm" src="https://cloud.githubusercontent.com/assets/1318077/13119029/55639f2a-d5a7-11e5-9041-51652b470f67.png">

Displaying only the ones that have been downloaded (same as the current behavior)
<img width="476" alt="screen shot 2016-02-17 at 6 49 45 pm" src="https://cloud.githubusercontent.com/assets/1318077/13119044/63c6ba2a-d5a7-11e5-87e0-b56e43fabd0f.png">

Showing only what is locally missing
<img width="477" alt="screen shot 2016-02-17 at 6 49 56 pm" src="https://cloud.githubusercontent.com/assets/1318077/13119062/7b746aaa-d5a7-11e5-86f8-7a6cbe786a0e.png">

**Comment by insidegui** [comment]
Implemented by https://github.com/insidegui/WWDC/pull/111

**Comment by lmihalkovic** [comment]
Just realized the screenshots show the flags being reversed... "downloaded" should show only entries WITHOUT the download arrow, while "missing" should only show entries WITH the download arrow available... sorry about that.
