### ISSUE TITLE
Improve URL support: search and time

### ISSUE THREAD

**Issue by tracicot** [insidegui/WWDC#114]
It would be great to be able to make an Alfred search/workflow to launch the app right into a search result.

**Comment by insidegui** [comment]
I don't use Alfred, what would be required of the app to get this functionality?

**Comment by tracicot** [comment]
I think its called a url scheme. Basically a way to send in a query string into the app and have the app launch and execute that query. Here's a document from 2Do for examples of how they handle such a feature. http://www.2doapp.com/url-schemes-in-ios-and-os-x/

**Comment by tracicot** [comment]
All you'd need is to provide that feature, and Alfred power users could make a shortcut to hook into the wwdc app themselves. Or I could make it and post it on the Alfred workflows forum and you could link to it.

**Comment by peterkos** [comment]
Something like this?
````
wwdc://viewVideo?year=[year]&track=[track]&focus=[focus]&sessionName=[name]
````
... with optional filters (to an extent). For instance, if the session name is supplied, there's no need to look for the year, track, and focus if the video already exists. Alternatively, if only the track, focus, or year are supplied, then return an array of possible options. (I haven't used Alfred before and am not sure of the context of this implementation)

For implementation reference: http://fredandrandall.com/blog/2011/07/30/how-to-launch-your-macios-app-with-a-custom-url/

**Comment by insidegui** [comment]
With v5, the app does not have a custom URL scheme anymore, but it does support `developer.apple.com/wwdc/*` URLs. Apple has its own scheme to open a video on a specific time, I think we should support that and add extra parameters for filtering.

**Comment by davedelong** [comment]
Time offsets are added to the url as a query item of the form `?time=360` (the value is the offset in seconds)

**Comment by davedelong** [comment]
Modifying `DeepLink` to pull the `time` value out of the URL is trivial; the harder bit would be telling the `AppCoordinator` to start playing the video at a specific time.

**Comment by davedelong** [comment]
I've been plumbing the time through. It's mostly working, except I noticed that linking to a specific video/session doesn't cause the detail area to update.

**Comment by ffittschen** [comment]
The deeplink could then be added to the calendar events like `Show in mail...`

**Comment by Linasses** [comment]
Not sure if this is a NEW feature request, or an elaboration on this one. How about Search results linking/highlighting text in the transcript. Then user click on the highlighted text moves the scrubber to the correct time stamp.
