### ISSUE TITLE
Better searching through slide PDFs

### ISSUE THREAD

**Issue by tracicot** [insidegui/WWDC#116]
It'd be more effective be able to search through the PDF slides. It might be easier though, to just provide a button to open with Preview (like QuickLook) to be searched there.

**Comment by insidegui** [comment]
I'll see what I can do, shouldn't be too hard to implement a simple search in there. For now you can just save the slides and open with Preview by hitting ⌘S

**Comment by tracicot** [comment]
This is awesome. Thanks a lot for implementing this!
