### ISSUE TITLE
Can't switch subtitles to Chinese when Watch HD Video

### ISSUE THREAD

**Issue by alfredcc** [insidegui/WWDC#118]
I can switch subtitles  to `Chinese`in SD Video, but HD Video.

**Comment by insidegui** [comment]
Apple doesn't provide subtitles on the downloadable HD files which are used when you select "watch in hd".

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (419/400 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:55967 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMi-000akA-2X
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:23 +0100
Date: Sun, 13 Mar 2016 21:11:56 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457928716;
	bh=oYwu15HZxOruhXHgAgaIudrt0M0xVf60CqK7LNFbCmE=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=dGFHe0Mi10rKyvA590qpCjES2k53qoeUmxxl87KESuhSKJLPTS2IPAkxDAK500YOl
	 gR3RRMg23HolieKYLfV6tdfWK6CujFU63n4CP2Ly6Zveqj8ZPQQM1GIfo8EgwY30CO
	 jiXJc4t/hmgvcV4MG5UtPdwNEf15qQDha2Pah0Y0=
