### ISSUE TITLE
Download overview

### ISSUE THREAD

**Issue by zortje** [insidegui/WWDC#12]
It would be nice with a way to view active downloads and a way to cancel downloads.

**Comment by art-divin** [comment]
I think it would be better to add a separate window like Safari downloads popup with all available tasks.

**Comment by insidegui** [comment]
I agree.

**Comment by art-divin** [comment]
@insidegui please review my pull request

**Comment by insidegui** [comment]
I will. Thanks.

**Comment by art-divin** [comment]
I think this issue can be closed now
