### ISSUE TITLE
Integration with existing downloaded videos

### ISSUE THREAD

**Issue by chandanankush** [insidegui/WWDC#120]
Hi Team,
First of all thanks for creating such a very good tool to watch wwdc sessions.

 I just have a simple enhancement request, i don't know whether it is already there. If it is there please let me know how to do that ?

So what is my problem is the videos i have already downloaded WWDC videos. can i map those wwdc sessions directly with this app.

I have downloaded all the videos 12 months back with this 
"https://github.com/ohoachuck/wwdc-downloader" tool. Please help me to map those videos, so that i can save the data and time to re-download those video again.

thanks again for writing such a great app..

**Comment by insidegui** [comment]
I think if you put the files in the folder where the app is looking for the videos It should work, assuming the filenames match. You can set the folder in preferences.

**Comment by zhenglaizhang** [comment]
@insidegui That's cool the app support the importing of existing sessions, thanks for the great work here. I just met with the same issue and so lucky i searched here and got this. 
How about adding the instruction to readme or make it explicit in the app's work flow?
