### ISSUE TITLE
don't find way for downloading SD video

### ISSUE THREAD

**Issue by phiren** [insidegui/WWDC#121]
Hi

don't find way for downloading SD videos, tapping on download button, it downloads HD video only.

**Comment by insidegui** [comment]
The app only downloads HD videos and I have decided to keep It that way.

**Comment by phiren** [comment]
ok, found one way
File: DownloadProgressViewController.swift
Function: download

@IBAction func download(sender: NSButton) {
        if session == nil {
            return
        }
        
		if let url = session.hd_url {
            print("The url is.....\(url)");
			//VideoStore.SharedStore().download(url)
		}
	}

It prints video URL, just change _hd_ with _sd_ and it works :)
