### ISSUE TITLE
Trying to download videos from 2013 fails

### ISSUE THREAD

**Issue by tkrajacic** [insidegui/WWDC#122]
When I download a video from 2013 the task stays without progress forever.
Looking in the console reveals that the nsurlsession task fails with error -1008 which is afaict "Too many redirects"

Do the URLs need to be updated?

On a sidenote, the 2012 videos are also available on Apple's site, so the app should display a download button for them I guess?

**Comment by jarrydfillmore** [comment]
Same here!

**Comment by insidegui** [comment]
This is working on v5.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. wwdc.io
