### ISSUE TITLE
Suggestion: Embed video in selected event page?

### ISSUE THREAD

**Issue by peterkos** [insidegui/WWDC#123]
Instead of having the video popup over the rest of the application and obscure it from the user's view, could the video be embedded within the event page? 

![wwdc_eventpackmockup](https://cloud.githubusercontent.com/assets/2782749/15271044/fa89a49a-1a03-11e6-8883-073aa58c7cb2.png)

(it was by coincidence that the NSCollectionView video was the same example shown in the readme)

**Comment by peterkos** [comment]
I'm not sure if the custom player view should be discarded altogether (as the transcript would be available right below the video), or just have the transcript functionality disabled in the windowed view. 

This might help fix #130, as in testing the bug didn't exist, so it's something to do with the custom view layout.

**Comment by insidegui** [comment]
@peterkos I never used a fully custom player view, the only thing that changed was that ugly speed button but I fixed this with the last update by moving the option to a menu item. I already have a new player implemented (It's in the `WWDCPlayer` framework) and It can start playing within another view and can be detached to another window. You can see how It's going to work here: http://twitter.com/_inside/status/739487249516138496/video/1

**Comment by insidegui** [comment]
This is implemented in v5, which should be available before this year's WWDC.

**Comment by insidegui** [comment]
Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
