### ISSUE TITLE
Question: App will not save favorites ?

### ISSUE THREAD

**Issue by brunov0id** [insidegui/WWDC#133]
When I favorite a video, then I close WWDC app, after when I open again, the app does not keep the favorites saved. It's correct ?

**Comment by insidegui** [comment]
It's a bug, probably solved by some of the changes I've made today. The update will be live soon.

**Comment by brunov0id** [comment]
Thank you 👍

**Comment by insidegui** [comment]
This issue is fixed in 4.0. Let me know if you have any problems.
