### ISSUE TITLE
Download is not properly signed, triggers gatekeeper warning.

### ISSUE THREAD

**Issue by invariant** [insidegui/WWDC#134]
<img width="532" alt="screen shot 2016-06-07 at 20 14 41" src="https://cloud.githubusercontent.com/assets/17520/15871430/816c884c-2cec-11e6-96a6-21a92dd62f95.png">
RB App Checker Lite:
![screen shot 2016-06-07 at 20 14 22](https://cloud.githubusercontent.com/assets/17520/15871416/73b11d94-2cec-11e6-8b6b-4faa633cb76d.png)

**Comment by insidegui** [comment]
Looks like Xcode decided to bundle Fabric and Crashlytics with the app instead of just linking, I think that's the problem. Thanks for letting me know!

**Comment by invariant** [comment]
Nice one, I confirm that the current build (4.1.1) validates fine.
