### ISSUE TITLE
Inconstancy with downloads from pre 2013

### ISSUE THREAD

**Issue by SoneeJohn** [insidegui/WWDC#136]
Using the latest release of the application (4.1.2 at the time of writing) the following happens:

- Right click on a session from pre 2013 (e.g. 2011) and the contextual menu has a download option.
 - However, the right split view, that has additional details does not contain a download button.

I uploaded screenshots to demo this. Note videos from pre 2013 cannot be downloaded therefore, having the download option in the contextual menu seems like an inconstancy IMO. Not a huge issue but, I was hoping to bring it to your attention.

![screen shot 2016-06-09 at 8 21 27 pm](https://cloud.githubusercontent.com/assets/4827301/15950812/4ac90a8c-2e80-11e6-9e11-8f00dd9faa0f.png)
<img width="467" alt="screen shot 2016-06-09 at 8 22 50 pm" src="https://cloud.githubusercontent.com/assets/4827301/15950813/4bd9c984-2e80-11e6-83dc-12ec0d3357f3.png">

**Comment by insidegui** [comment]
I am aware of this, It is a usability issue and will definitely be fixed. Thanks for reporting.

**Comment by SoneeJohn** [comment]
@insidegui I think if fixed this with this PR: #137
