### ISSUE TITLE
Access to this event store is unathorized

### ISSUE THREAD

**Issue by agucova** [insidegui/WWDC#141]
So, whenever I try to click "Create Reminder", I get this:
![Bug?](https://i.imgur.com/aPdHtkW.png)
I installed via brew cask, and I'm running OSX 10.11.15 (El Capitan).

**Comment by insidegui** [comment]
It should have asked permission to you on the first try to allow calendar access. Check in System Preferences > Security & Privacy > Privacy, under "Reminders" if WWDC is listed there and checked:

![captura de tela 2016-06-13 as 21 47 05](https://cloud.githubusercontent.com/assets/67184/16027894/6b3daa24-31b0-11e6-83cc-5764f08e7657.png)

**Comment by agucova** [comment]
Maybe I upgraded from an older version without requiring permissions? Look:
![Emmm.....](https://i.imgur.com/qMFeOqw.png)
Its in Spanish, but you can see the app it's not even listed. (neither on calendar or accessibility)

**Comment by insidegui** [comment]
That is weird, the system should show you a dialog asking for your permission if the app is not listed in there. I had the old version and It worked for me.

I will craft a special build for you to run on your system to diagnose this issue, I'll send It here tomorrow. Thanks for reporting!

**Comment by insidegui** [comment]
Please [run this special build of the app](https://dl.dropboxusercontent.com/u/452482/WWDC_141_b1.zip) and try to create a reminder for any of the scheduled sessions. Make sure to close the current version of the app if It's already running.

After you run and click the "Create Reminder" button there will be a file on your Desktop named `WWDC_Reminders_Log.txt`, please send me the file or It's contents.

Thanks!

**Comment by uchuugaka** [comment]
Check the code signing. If it's broken after install you might not get some things to work.

**Comment by insidegui** [comment]
I'm closing this issue since it is not applicable anymore with the release of v5.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
