### ISSUE TITLE
Question: why did my favorites disappeared ?

### ISSUE THREAD

**Issue by brunodlz** [insidegui/WWDC#143]
Hey, day before yesterday I received a new update, however I had several favorites marked before upgrading, now I just have a favorite.

**Comment by insidegui** [comment]
Sorry about that, do you have backups? If you do, let me know and I'll try to help you recover your data.

**Comment by brunodlz** [comment]
No problem, I just updated the app, I do not remember their backup.

**Comment by insidegui** [comment]
Hm, ok. But if you have a time machine backup It's recoverable 😅

**Comment by brunodlz** [comment]
Sure, in the next update, I will backup the favorites 😅
Thank you.
