### ISSUE TITLE
Forgetting favourites after sessions occur.

### ISSUE THREAD

**Issue by vitorgalvao** [insidegui/WWDC#145]
For the second time this WWDC, the app has forgotten some of my favourites.

I favourited all the sessions I want to see, even the ones that haven’t happened yet. Today, I checked the app and all my favourited sessions that already happened (but that I haven’t seen) were gone from the favourites. Only the ones that haven’t happened yet stayed favourited.

**Comment by vitorgalvao** [comment]
Thank you.

**Comment by insidegui** [comment]
Release will be up soon. Sorry about that!

**Comment by vitorgalvao** [comment]
No problem. Thank you again for the quick fix and the great app.
