### ISSUE TITLE
Missing ⌘H shortcut

### ISSUE THREAD

**Issue by benjamincrozat** [insidegui/WWDC#146]
I'd love if this could be fixed. I prefer hiding windows over minimizing and more important, most apps support it anyway.

Keep on the good work!

**Comment by insidegui** [comment]
I use ⌘H all the time, It works here...

**Comment by benjamincrozat** [comment]
So you close this issue assuming that I'm hallucinating? Very good attitude.

Anyway, I think the app is great so I take the time to give you the steps to reproduce: two screens, the main window on the main screen, and a fullscreen video playing on the second screen. You can't hide the main window (you have to close it or minimize it).

**Comment by insidegui** [comment]
Fuck you (and your two screens).

**Comment by insidegui** [comment]
Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
