### ISSUE TITLE
"Mark as watched" resets randomly

### ISSUE THREAD

**Issue by MuscleRumble** [insidegui/WWDC#148]
This is hard to reproduce, but sessions "marked as watched" don't stay that way. They randomly get "unwatched", probably when quitting/starting the app again. It's also not consistent. It happens all over the place, not only for recently marked sessions. That means, sessions that I've marked weeks/months ago randomly get unmarked.

For older sessions this is really unfortunate, because I can't remember every single session I've already watched.

**Comment by insidegui** [comment]
Can you confirm this is happening on the latest release (4.2.2)? There was a bug with favorites which also affected watched status, I released 4.2.2 today.

**Comment by MuscleRumble** [comment]
Thanks! I've updated the app and I'll keep an eye out on this issue. 😄 I'll just reopen this issue, if the bug reappears. Thanks for your great work!
