### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by bre7** [insidegui/WWDC#149]
Minor UX improvements:

* Disable menu options taking into account the clicked item's current status (e.g: Disable "Mark as unwatched" if the element isn't marked as watched)
* Update progress on the tableview while a video is being downloaded. Might trigger too many tableview reloads when downloading multiple files.

**Comment by insidegui** [comment]
There's already a pull request implementing your first suggestion (I think), but we're not doing any major changes to the app during this week for obvious reasons. After this WWDC is over this app is going to get a major overhaul with lots of improvements :)

Thanks for contributing!

**Comment by bre7** [comment]
I'll comment directly on #137 for the first point ;)

> After this WWDC is over this app is going to get a major overhaul with lots of improvements :)


Awesome !

**Comment by bgerstle** [comment]
> After this WWDC is over this app is going to get a major overhaul with lots of improvements :)

@insidegui do you plan to publish a feature roadmap so people interested in contributing can coordinate on the improvements you have in mind?

**Comment by insidegui** [comment]
Yes I do, I should have done It already 😆

**Comment by bgerstle** [comment]
Not like there's anything important going on right now 😜
