### ISSUE TITLE
Sync user data between multiple computers

### ISSUE THREAD

**Issue by juanpdelat** [insidegui/WWDC#150]
I'd love to be able to synchronize the videos' status between my home and work computers so I don't have to go to the list and check which ones I have already seen.

**Comment by insidegui** [comment]
Now that apps outside the AppStore can use iCloud this has become possible, so It's definitely coming in the future :)

**Comment by peterkos** [comment]
Could this possibly be implemented with CloudKit so users wouldn't have to sign-in?

**Comment by insidegui** [comment]
Yeap, the only reason the app doesn't have syncing yet is the lack of iCloud support for apps distributed outside the store.

**Comment by EvgenyKarkan** [comment]
@juanpdelat, I guess you love your working place, cuz you can watch WWDC at work :)

**Comment by insidegui** [comment]
This is being worked on for v5. Thanks for reporting.
