### ISSUE TITLE
Issues related to downloads

### ISSUE THREAD

**Issue by uraimo** [insidegui/WWDC#151]
Thanks for this useful app, a few things i noticed related to downloads:
- The pie chart download indicator seems to be partially broken (always has been afaik), sometimes the progress shown is from one the other downloads (e.g. new download, shows the progress of some other file)
- When the download completes and the file is moved to its final location the UI freezes. Other than doing this final operation in another thread, couldn't we start the download directly into the final video directory?
- Once you start a few downloads there is no way to see a recap of the files being downloaded, having another category where we now have _downloaded_ and _missing_ could be a good idea (something like "_in progress_"?).

**Comment by insidegui** [comment]
This part of the app is going to be completely redone on the next major release.

**Comment by insidegui** [comment]
I'm closing this since it's not applicable anymore with v5. If you see any other issues, please don't hesitate to report them.

Version 5 is available now on wwdc.io and the update for users of older versions will come later this week.
