### ISSUE TITLE
Main window is named "Untitled" in the Window menu

### ISSUE THREAD

**Issue by philippec** [insidegui/WWDC#153]
If you pull down the "Window" menu, you will notice that the main window is listed as "Untitled".

**Comment by insidegui** [comment]
😆

**Comment by insidegui** [comment]
Do you mean the about window? The main window shows as "WWDC" and all other windows have their correct titles, but the about window shows up as "Window".

**Comment by philippec** [comment]
No, I do mean the Main window. Here's a screenshot. Note that this is on macOS Sierra, so maybe it's OS-dependent. I should have said that before, sorry!

<img width="1280" alt="capture d ecran 2016-06-17 a 09 37 36" src="https://cloud.githubusercontent.com/assets/74659/16157871/5b235e9c-346f-11e6-84a6-1d5226833e64.png">

**Comment by insidegui** [comment]
I see, maybe It's a beta bug since It's working on El Cap, let's wait for the next releases...
