### ISSUE TITLE
Allow cancelling and removing downloads (not just pausing them)

### ISSUE THREAD

**Issue by tonyarnold** [insidegui/WWDC#155]
It would be great to be able to cancel, remove and clear downloads I don't want to complete. Right now, I end up with screens of "Paused" downloads. 

<img width="593" alt="screen shot 2016-06-17 at 16 35 05" src="https://cloud.githubusercontent.com/assets/4802/16167433/b814b8f0-34a9-11e6-97f4-0997f6d14582.png">

(Is there a way to clear these in the current release?)

**Comment by insidegui** [comment]
Select the download(s) and press delete 😉

**Comment by tonyarnold** [comment]
One. At. A. Time. 

Want a separate issue for that? I know you're planning on rebuilding this component post WWDC16.

**Comment by insidegui** [comment]
Yes, please. I didn't realize It since I don't use this feature much 🙃

**Comment by mackuba** [comment]
Is there any way to access a list like this (downloads in progress) in the new app?

**Comment by insidegui** [comment]
Not currently. This is on the list for implementation soon.
