### ISSUE TITLE
Trouble building project

### ISSUE THREAD

**Issue by SoneeJohn** [insidegui/WWDC#161]
Using Xcode 7.3.1 on macOS 10.11.6:
 
Clone project (changed directory to ~/Desktop/test): 

```git clone --recursive https://github.com/insidegui/WWDC.git```

Output:

```
Cloning into 'WWDC'...
remote: Counting objects: 2992, done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 2992 (delta 40), reused 0 (delta 0), pack-reused 2915
Receiving objects: 100% (2992/2992), 92.44 MiB | 394.00 KiB/s, done.
Resolving deltas: 100% (1722/1722), done.
Checking connectivity... done.
```

`pod install`

Output:
```
Re-creating CocoaPods due to major version update.
Analyzing dependencies
Fetching podspec for `WWDCAppKit` from `LocalPods/WWDCAppKit`
Fetching podspec for `WWDCPlayer` from `LocalPods/WWDCPlayer`
Downloading dependencies
Installing Alamofire (3.4.0)
Installing KVOController (1.1.0)
Installing Realm (1.0.0)
Installing RealmSwift (1.0.0)
Installing Sparkle (1.14.0)
Installing SwiftyJSON (2.3.2)
Using WWDCAppKit (1.0.0)
Using WWDCPlayer (1.0.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `WWDC.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 7 dependencies from the Podfile and 8 total
pods installed.

```
Opens workspace and attempts to build project, got these errors:
`Could not build Objective-C module 'Realm'`
` Umbrella header 'Realm.h' not found`

**Comment by insidegui** [comment]
I see, you're using a beta OS. You should always use the latest stable OS release when working on this project since many of the tools used to build It may not support the first developer beta yet. I will migrate the project to the new toolchain in macOS later (probably when the public beta gets released).

**Comment by insidegui** [comment]
I will add a note to the readme about this.

**Comment by arthurhammer** [comment]
I'm seeing the exact same issue and I'm not on the beta. I'm on El Capitan, 10.11.5.

**Comment by arthurhammer** [comment]
Alright, seems to be working now. Removed derived data, cleaned the project, deintegrated and then reinstalled pods.

**Comment by insidegui** [comment]
Yeah Xcode can be tricky sometimes, when you have issues like this just delete all derived data and module cache and try again ;)
