### ISSUE TITLE
Resume downloads after relaunching app (instead of marking incomplete: "Complete")

### ISSUE THREAD

**Issue by iandundas** [insidegui/WWDC#163]
Currently quitting and relaunches the app marks all downloads that were "In Progress" as completed. Trying to play the video shows that the video is broken. The falsely "completed" files are all 3KB in the Application Support folder.

Either: 
- resume the downloads on relaunch, or
- clear the incomplete files and restore state as not downloaded (less good)

otherwise all excellent. Thanks!

**Comment by insidegui** [comment]
The app should resume the downloads when relaunched, [here's It working on the latest version (4.2.4)](https://www.dropbox.com/s/6r67n2qr8o7eunp/DownloadResume.mov?dl=0).

Can you give me more details about your setup (OS version, computer model, internet connection, etc)?

**Comment by iandundas** [comment]
Just updated to 4.2.4 - previously had a release from a few days ago. Let me check it now

**Comment by iandundas** [comment]
Yes - works now. Will keep an eye on it, seems great now. Cheers

**Comment by insidegui** [comment]
If you encounter this problem again, just reopen the issue. Thanks.
