### ISSUE TITLE
Sessions named equally from different years

### ISSUE THREAD

**Issue by isolution-de** [insidegui/WWDC#164]
There seems to be a problem with sessions from different years that already exist in the video directory. I have the "Platforms state of the union" from 2015 in the directory and the app thinks this is the video from 2016 AND 2015. Maybe there should be different subdirectories for each year?

I downloaded last years videos with last years version of the app, installed the new version and set the video directory to the existing directory. Maybe that was the issue? Or is anyone else having the same issue?

**Comment by insidegui** [comment]
You're having a problem with the downloads because the session titles are the same, It's interesting that no one had noticed this yet 😅

It's definitely a bug and should be fixed, your idea of using directories sound good.

**Comment by PaulWaldo** [comment]
@insidegui it was noticed, I just have been lazy reporting it 😳

**Comment by PaulWaldo** [comment]
A folder per year would be very nice for organization.  I also link these videos to iTunes so I can play them remotely from my Apple TV.

**Comment by insidegui** [comment]
This is fixed with v5, the downloaded videos are separated in subdirectories for each year.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
