### ISSUE TITLE
Unable to view transcript with video

### ISSUE THREAD

**Issue by kylegrussell** [insidegui/WWDC#165]
While watching a video if you select View > Transcript the app crashes
v4.2.4

**Comment by insidegui** [comment]
What OS are you running and which video did you try to open the transcript for?

Thanks!

**Comment by kylegrussell** [comment]
El Capitan v10.11.2
I tried the Keynote, What's New in Swift, What's New in Cocoa and Getting Started in Swift (all from 2016). The app crashed on all the videos. I went into Preferences and reindexed the transcripts as well in case that might help.

**Comment by insidegui** [comment]
The transcripts are not available for this year's sessions yet, but the app should not crash, it should just do nothing in this case. I don't know why it's crashing on your system...

**Comment by insidegui** [comment]
[Fabric](https://fabric.io) just sent me your crash logs, I know what's happening. Fix coming soon.

Thanks for reporting ✌🏼

**Comment by kylegrussell** [comment]
Gracias! Yeah I figured the 2016 transcripts weren't available yet after I tried a few videos but then it started crashing.
Love the app though!
