### ISSUE TITLE
Brew cask install fails

### ISSUE THREAD

**Issue by AndrewSB** [insidegui/WWDC#166]
Currently the brew cask install is failing for me, I've tried `brew update`ing. I am on macOS Sierra, but I don't think it's related to that, seems like an issue with the zip maybe?

```
==> Downloading https://github.com/insidegui/WWDC/releases/download/4.2.3/WWDC_v4.2.3.zip
######################################################################## 100.0%
==> Verifying checksum for Cask wwdc
Error: Uh oh, could not figure out how to unpack '/Users/asb/Library/Caches/Homebrew/wwdc-4.2.3.zip'
```

**Comment by insidegui** [comment]
@nanoxd can you take a look at this? Thanks!

**Comment by AndrewSB** [comment]
Was able to download the zip from the Github release page fine.

Also I noticed that brew doesn't have the latest version of the WWDC app

**Comment by insidegui** [comment]
Brew cask install has been updated to v5.
