### ISSUE TITLE
Crash when opening video via URL

### ISSUE THREAD

**Issue by arthurhammer** [insidegui/WWDC#167]
e.g. wwdc://2016/223

WWDC 4.2.4
OS X 10.11.5

**Update**: Gave it a quick look. The problem is `VideoWindowController` [here](https://github.com/insidegui/WWDC/blob/master/WWDC/URLSchemeHandler.swift#L57) goes out of scope and is dealloced while the video starts/plays. If you put it as a property on the `URLSchemeHandler`, it doesn't crash. But I don't know if that would be the right place for it.

**Update**: Actually, it seems you can start any number videos via URL. So you would have to retain each `VideoWindowController` created in `URLSchemeHandler` somewhere.

**Comment by insidegui** [comment]
Good catch! ✌🏼

**Comment by funky-monkey** [comment]
+1

**Comment by insidegui** [comment]
V5 doesn't use the custom URL scheme anymore, but it can open `developer.apple.com/wwdc/*` links, so I think this issue can be closed now. Thanks for reporting.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
