### ISSUE TITLE
Moving to the exact next/previous pages in slides

### ISSUE THREAD

**Issue by Nyoho** [insidegui/WWDC#168]
I would like to move the _exact_ next or previous page in the slide view when I look at slides PDFs. Now space key works as a halfway moving in slide view.
I wrote some lines to WWDC/PDFWindowController.swift to add a feature of moving the exact next or previous page of the PDF.  Could I create a pull request about that?

**Comment by insidegui** [comment]
Sure! :)

**Comment by Nyoho** [comment]
Thank you! I've created a pull request (169).

**Comment by insidegui** [comment]
On v5 I decided to just open the slides on the default browser, I don't think it's worth to have a built in PDF viewer since there's Preview and other apps which are much better at that.

**Comment by Nyoho** [comment]
I see! I checked out the current master branch and It's good.

I feel easier to use a build-in viewer for slides because when I open the slides of the session that I'm watching, I want to operate the next/previous slide moving without switching to other apps (command + tab or something). But it's my personal feeling.
