### ISSUE TITLE
Possible bug: changing UI from background thread

### ISSUE THREAD

**Issue by art-divin** [insidegui/WWDC#17]
I think that method
`URLSession(session: NSURLSession, downloadTask: NSURLSessionDownloadTask, didFinishDownloadingToURL location: NSURL)` is usually called from background thread, however, a notification like `NSNotificationCenter.defaultCenter().postNotificationName(VideoStoreNotificationDownloadFinished, object: originalAbsoluteURLString)` is [being sent][1] directly from networking queue.

I have absolutely no experience in OS X development, but as for iOS - this is a "no-no".

[1]: https://github.com/insidegui/WWDC/blob/master/WWDC/VideoStore.swift#L106

**Comment by insidegui** [comment]
The subscriber can specify in what thread it wants the notification listener to be called. I can't check it right now because I'm not home.

**Comment by art-divin** [comment]
Thanks. I am too used to `-[NSNotificationCenter addObserver:selector:name:object:]`
