### ISSUE TITLE
was it able to select subtitles other than English?

### ISSUE THREAD

**Issue by walkerwzy** [insidegui/WWDC#171]
like Chinese?

**Comment by insidegui** [comment]
Some sessions have subtitles in various languages (including Chinese), but not all of them. The sessions from 2015 do have Chinese subtitles but this year's sessions don't.

**Comment by walkerwzy** [comment]
yes, I watched some 2015 sessions, and it do have Chinese subtitles but, only in the low definition version. the HD version still only have English subtitle, what's the reason?

**Comment by insidegui** [comment]
I don't know. The videos come straight from Apple's server, there's nothing I can do in this case :/
