### ISSUE TITLE
Downloaded videos list does not reflect the latest

### ISSUE THREAD

**Issue by deepumukundan** [insidegui/WWDC#172]
![screen shot 2016-06-28 at 4 49 46 pm](https://cloud.githubusercontent.com/assets/1459484/16436159/67e0f100-3d50-11e6-8f25-aa71f002160c.png)

Attached screenshot. Here I have toggled to show only downloaded videos. I only have the 3 with the blue icon on the right on my mac. The rest I had downloaded, watched and deleted. The list is not picking up the right contents even after a reboot.

Is the app looking at the folder of downloads to build the list or does it keep a separate index?

**Comment by insidegui** [comment]
The app monitors the downloads folder but the search results come from the database which should be updated when the files change, but looks like we have a bug in this process 😁

**Comment by insidegui** [comment]
I'm closing this issue since it is not applicable anymore with the release of v5.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
