### ISSUE TITLE
quit app. rebooted mac. app not set to launch on its own. yet it launches process to continue downloads in background.

### ISSUE THREAD

**Issue by aceneerav** [insidegui/WWDC#173]
![screen shot 2016-07-02 at 7 00 17 pm](https://cloud.githubusercontent.com/assets/2323035/16540585/99b93bc6-4087-11e6-840b-cda06f36d5db.png)

**Comment by insidegui** [comment]
This is standard behavior of Apple's NSURLSession.

**Comment by aceneerav** [comment]
But how is the NSURLSession initiated without the app being launched after a reboot?

I have made an iOS app so not sure how it works on os x

**Comment by insidegui** [comment]
When the app is terminated with a pending download task, the system keeps the NSURLSession daemon running to finish the task.

**Comment by aceneerav** [comment]
But how does it launch the task after reboot when the app hasnt been launched yet?

**Comment by insidegui** [comment]
It's a system thing, I don't know how it's implemented, I don't work at Apple...
