### ISSUE TITLE
The video does not have the transcript synced with AsciiWWDC

### ISSUE THREAD

**Issue by Leon16** [insidegui/WWDC#174]
I am running the WWDC 4.3 and try to play one of the session video. However there is no option for me to show the synced transcript from ASCiiWWDC. The only transcript is from within the video

**Comment by insidegui** [comment]
Which session are you trying to watch?

**Comment by Leon16** [comment]
I was viewing session 208  What's New in watchOS 3 of WWDC 2016. I thought I need to download the video and allow the app to do indexing. I did it but still could not see the sync'ed transcript

**Comment by insidegui** [comment]
I'm closing this issue since it is not applicable anymore with the release of v5.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
