### ISSUE TITLE
fix ordering sessions by year and id

### ISSUE THREAD

**Issue by mackuba** [insidegui/WWDC#175]
It seems the ordering has been recently changed (https://github.com/insidegui/WWDC/commit/26982f3f60b0bc90060a78f5e9760f4f132e794d) to sort the sessions using the `schedule` property. However, this doesn't seem to make much sense to me, at least now, after the WWDC has ended. This is how the list looks now: 101, 102, 103, 401, 201, 202, 402, 801, 701, 601... At first glance they don't seem to be ordered by anything at all.

![screen shot 2016-07-15 at 18 30 03](https://cloud.githubusercontent.com/assets/28465/16881396/475ce606-4aba-11e6-9c51-af08cc92bf5d.png)

**Comment by insidegui** [comment]
This is fixed in v5, which should be available before this year's WWDC ;)

**Comment by insidegui** [comment]
Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
