### ISSUE TITLE
prefix downloaded video names with a year (or add subdirectories)

### ISSUE THREAD

**Issue by mackuba** [insidegui/WWDC#176]
Currently the videos are saved with their original names, but this creates naming collisions between videos from different years. I had the 2015 keynote downloaded, and the app showed that I have the 2016 keynote - I removed it, redownloaded the 2016 keynote, and now it's still showing that I have both keynotes, even though I only have the new one :)

**Comment by PaulWaldo** [comment]
I also experience this problem

**Comment by insidegui** [comment]
This is solved in v5, which should be available before this year's WWDC ;)

**Comment by insidegui** [comment]
Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
