### ISSUE TITLE
Build issue on Xcode7.2, OS10.10.5

### ISSUE THREAD

**Issue by chenzhijie** [insidegui/WWDC#177]
Hello! I clone the repo recursive and pod install after pull the source code.  When I build it in Xcode7.2 ,some swift syntax errors happen. My mac os is 10.10.5.

Error message:

expected expression after operator
                if selector == #selector(NSURLSessionDelegate.URLSessionDidFinishEventsForBackgroundURLSession(_:)) {
                               ^
error: braced block of statements is an unused closure
                if selector == #selector(NSURLSessionDelegate.URLSessionDidFinishEventsForBackgroundURLSession(_:)) {
                                                                                                                    ^
expected pattern
            case #selector(NSURLSessionDelegate.URLSession(_:didBecomeInvalidWithError:)):
                 ^
expected ':' after 'case'
            case #selector(NSURLSessionDelegate.URLSession(_:didBecomeInvalidWithError:)):
                 ^
expected expression
            case #selector(NSURLSessionDelegate.URLSession(_:didBecomeInvalidWithError:)):
                 ^
expected pattern
            case #selector(NSURLSessionDelegate.URLSession(_:didReceiveChallenge:completionHandler:)):
                 ^
expected ':' after 'case'
            case #selector(NSURLSessionDelegate.URLSession(_:didReceiveChallenge:completionHandler:)):
                 ^
expected expression
            case #selector(NSURLSessionDelegate.URLSession(_:didReceiveChallenge:completionHandler:)):
                 ^
expected pattern
            case #selector(NSURLSessionTaskDelegate.URLSession(_:task:willPerformHTTPRedirection:newRequest:completionHandler:)):
                 ^
expected ':' after 'case'
            case #selector(NSURLSessionTaskDelegate.URLSession(_:task:willPerformHTTPRedirection:newRequest:completionHandler:)):
                 ^
expected expression
            case #selector(NSURLSessionTaskDelegate.URLSession(_:task:willPerformHTTPRedirection:newRequest:completionHandler:)):
                 ^
expected pattern
            case #selector(NSURLSessionDataDelegate.URLSession(_:dataTask:didReceiveResponse:completionHandler:)):
                 ^
expected ':' after 'case'
            case #selector(NSURLSessionDataDelegate.URLSession(_:dataTask:didReceiveResponse:completionHandler:)):
                 ^
expected expression
            case #selector(NSURLSessionDataDelegate.URLSession(_:dataTask:didReceiveResponse:completionHandler:)):
                 ^
expected expression in list of expressions
                protocol: URL.scheme,
                ^
expected ',' separator
                port: URL.port?.integerValue ?? 0,
                                                  ^
                                                  ,
expected ')' in expression list
                protocol: URL.scheme,
                ^
/Users/chenziacke/Desktop/WWDC/Pods/Alamofire/Source/Request.swift:502:55: note: to match this opening '('
            let protectionSpace = NSURLProtectionSpace(
                                                      ^
expected identifier in protocol declaration
                protocol: URL.scheme,
                        ^
expected declaration
    associatedtype SerializedObject
    ^

**Comment by insidegui** [comment]
Hi! The app does not support 10.10 anymore and building it requires Xcode 7.3 or later and will soon require Xcode 8 or later.
