### ISSUE TITLE
Skip forward and backward by 15/30 seconds in video

### ISSUE THREAD

**Issue by sfsam** [insidegui/WWDC#178]
It would be useful to be able to quickly skip forward and backward in increments of 15 and 30 seconds. Could we have buttons on the video player (and keyboard equivalents) for this?

Particularly for technical material like WWDC videos, it is useful to be able to repeat what a speaker has just explained so you are sure you understand it.

Thanks for making a great app.

**Comment by insidegui** [comment]
This will be available on v5. Thanks.

**Comment by insidegui** [comment]
Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
