### ISSUE TITLE
Fix offline watching

### ISSUE THREAD

**Issue by lmihalkovic** [insidegui/WWDC#179]
The app support downloading videos. During playback the viewer does not check if the video is local and systematically plays from the remote location.

**Comment by insidegui** [comment]
Selecting "watch in HD" always plays the local file when available, but this is definitely an usability issue and should be fixed.

**Comment by insidegui** [comment]
I'm closing this issue since it is not applicable anymore with the release of v5.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
