### ISSUE TITLE
Fix download cancellation

### ISSUE THREAD

**Issue by lmihalkovic** [insidegui/WWDC#180]
When following the following series of steps
- start several downloads
- exist the app before the end
- restart

The following situation happened in several instances (not always): the download never completes and it is impossible to resume or cancel it from the downloads list.

**Comment by insidegui** [comment]
Maybe this is related to #147

**Comment by insidegui** [comment]
I'm closing this issue since it is not applicable anymore with the release of v5.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
