### ISSUE TITLE
No longer see transcripts after re-indexed

### ISSUE THREAD

**Issue by pkasson** [insidegui/WWDC#181]
I downloaded many sessions, and moved them to a network storage place.  I THINK it is playing them fine (I changed the location in prefs), but, before I did that, I could see the 'transcripts' / video sections to jump to, but no longer do, even after re-indexing.

**Comment by insidegui** [comment]
I don't thing moving the video files would have any effect on the transcripts. Have you tried re-reindexing?

Also, try moving the videos back to the default location and changing it on preferences to see if the problem persists.

**Comment by insidegui** [comment]
I'm closing this issue since it's not applicable anymore in v5. Please let me know if you find anything else on this new release. Thanks

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
