### ISSUE TITLE
Picture in picture

### ISSUE THREAD

**Issue by makoni** [insidegui/WWDC#182]
Is it possible to update the app to make Picture in picture mode available for video player?

**Comment by insidegui** [comment]
Not yet, I'm working on a big update for 5.0. If someone wants to send a pull request with this, fell free.

**Comment by diejmon** [comment]
Looks like there is no open API for PIP in macOS Sierra. http://stephenradford.me/hacking-macos-sierras-pip/

**Comment by insidegui** [comment]
@diejmon Correct. I'll have to implement it myself like I did for [Apple Events](https://github.com/insidegui/AppleEvents) or use the private API.

**Comment by insidegui** [comment]
I will probably be using [PIPContainer](https://github.com/insidegui/PIPContainer) to implement this ;)

**Comment by insidegui** [comment]
This is being worked on for v5. Thanks for reporting.

**Comment by insidegui** [comment]
PIP is available in v5.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
