### ISSUE TITLE
Missing: Changing Playback Rate to normal rate

### ISSUE THREAD

**Issue by muescha** [insidegui/WWDC#185]
I accidently activated faster playback rate

it was very hard to get it back to 1x rate.

i tried `cmd+shift+r` but not working. no changes.
i tried mouse click on the rate `2x`. but they changed from `2x` to `4x` up to `60x` but not cycle to `1x`
i tried to click `pause` then `play` - still on 2x
i tried to click on the backward play. but it switches from `forward 2x` directly to `backward 2x` i expected in between a switch to `1x` but no luck

it was very hard to get it back. maybe i need to hit many times `cmd+shift+r` before i get it back to `1x`

i think there should be a label `1x` or someting where i can easy reset the playback rate. and not hidden with this shortcut

**Comment by insidegui** [comment]
With version 5, there's now a speed button on the video controls that cycles through the available speeds.

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
