### ISSUE TITLE
Change Font Size 

### ISSUE THREAD

**Issue by muescha** [insidegui/WWDC#187]
i like to change the font size with `cmd -` or `cmd +` at lest at the session description. on big monitors it's very small

**Comment by insidegui** [comment]
Can you send me a screenshot showing this issue? Thanks!

**Comment by muescha** [comment]
i think it is normal size. but it is too small for my eyes. 

with a browser like Chrome/Firefox i can fast increase the font and and all is ok for me. 

thats why my feature request.

**Comment by insidegui** [comment]
V5 uses bolder and larger fonts so I think it fixes this issue :)

Version 5 is available as a pre release download now and users of the previous version will get the automatic update later this week. [wwdc.io](https://wwdc.io)
