### ISSUE TITLE
UI/UX design tweaks

### ISSUE THREAD

**Issue by VicenteBorrell** [insidegui/WWDC#192]
Don't be overwhelmed @insidegui , (I hope) they're easy to change :)

Tweaks:
- [x] Change session/video title font weight inside Cell to Medium.
- [x] Change session/video title font weight in Video Detail to Bold with -1 spacing.
- [x] Change Videos section icon to filled glyph when selected (it's in the UI Kit)
- [x] Change Video detail background color to black
- [x] Have a default window width/height. Should be enough to fit the sidebar and video detail (almost as big as the Sketch design but windowed with some space around, and centered).
- [ ] Select first session in Schedule by default on first launch (after loading)
- [x] Have a fixed video height (sometimes the fullscreen icon is hidden).
- [x] Move Cell text up some pixels (does not look vertically centered)
- [ ] Placeholder thumbnail doesn't load if there's no internet
- [x] Add vertical space between Top bar and video (see Sketch)
- [x] Action icons in Video Detail should be the active color (for UX)
- [x] Favorite icon in Video Detail should be filled when selected
- [ ] Closing PiP (using the "x" button) shouldn't change current selected video and shouldn't return focus to the app.
- [ ] Picture in Picture placeholder text Title color should be the same as the icon, like on the Sketch design.

Bug?
- [x] Top bar changes color in fullscreen

Nice to have
- [x] Press spacebar to pause and play video
- [ ] Allow rubberband scroll on video detail

**Comment by insidegui** [comment]
> Closing PiP shouldn't change current selected video
Until we have another way for the user to go back to the currently playing session, I think this should be the default behavior. Otherwise we'll put the user into a situation where he/she must go through the lists trying to find where the hell the video is playing (similar situation to having a video playing on a browser somewhere and not knowing exactly which window/tab it is)

> and shouldn't return focus to the app.
Just to be clear: you mean clicking the little "X" on the PiP, not the "reattach" button on the PiP, right? I have to figure out how I can know which one got pressed, because currently I only have one callback that is called for both of them.

**Comment by VicenteBorrell** [comment]
Yeah, I mean the X. When you return from PiP, it should go to the Video Detail, but if you close it, you don't want to go back to that view or the app if you are doing other things.

**Comment by insidegui** [comment]
Also I noticed that Safari pauses the video when the PiP is closed using the "X", we should do that too (if I can figure out how to get the right callback)

**Comment by VicenteBorrell** [comment]
Yeah, in the case the video is paused with X, it should show that video's detail.

**Comment by VicenteBorrell** [comment]
Hey @insidegui !

I reviewed the latest alpha and some changes aren't working: 
- Change session/video title font weight in Video Detail to Bold with -1 spacing.
- Picture in Picture placeholder text Title color should be the same as the icon, like on the Sketch design.

And you changed the color of the Video Player controls! (not sure if on purpose or not XD) Can you revert it to white, please?

By the way, I'm not digging the controls background (makes it look to big/blocky). Can you make a release without it to see how it looks like? I think I prefer the current YouTube style of having a gradient (maybe it's not necessary for most of the videos, that's why I want to test it).

Thanks! Keep up the great work! 🤙

**Comment by insidegui** [comment]
@VicenteBorrell Please check with the [latest alpha (7)](https://github.com/insidegui/WWDC/releases/tag/5.0-A7) and update the issue 🤓

**Comment by VicenteBorrell** [comment]
OK, I'll do it now 👍

**Comment by VicenteBorrell** [comment]
I updated the list after reviewing the latest changes @insidegui 👍

**Comment by VicenteBorrell** [comment]
Video title should look like this:
<img width="549" alt="screen shot 2017-05-15 at 23 34 02" src="https://cloud.githubusercontent.com/assets/584834/26378201/c7c68b2c-4013-11e7-8818-330a5970d9f7.png">
