### ISSUE TITLE
Video aligns to top after maximizing it

### ISSUE THREAD

**Issue by VicenteBorrell** [insidegui/WWDC#193]
When you maximize a video, the video clips to the top and stays that way after going back to windowed mode.

**Comment by VicenteBorrell** [comment]
<img width="972" alt="screen shot 2017-05-23 at 22 24 28" src="https://cloud.githubusercontent.com/assets/584834/26378139/8053034c-4013-11e7-92d2-618bd64b31d5.png">

**Comment by insidegui** [comment]
I was unable to reproduce this. Can you try it on the latest alpha?

**Comment by VicenteBorrell** [comment]
Yeah, it happens in the latest alpha too (9)
You have to maximize the video (not the window) and then you see it. And when minimizing it stays like that.

**Comment by insidegui** [comment]
It doesn't happen here. You mean putting the video in fullscreen, right?

**Comment by VicenteBorrell** [comment]
Yes.
