### ISSUE TITLE
Feature Request: integrate asciiwwdc.com

### ISSUE THREAD

**Issue by k06a** [insidegui/WWDC#2]
Add ability to search through http://asciiwwdc.com

**Comment by insidegui** [comment]
Good idea, I'll look into that.

**Comment by CameronBanga** [comment]
:+1:

**Comment by skywinder** [comment]
@insidegui can't figure out, how to use it. Can you provide some examples?

**Comment by insidegui** [comment]
During video playback go to View > Transcript

**Comment by SatanWoo** [comment]
cool!

**Comment by k06a** [comment]
@insidegui is it possible to search via texts?

**Comment by insidegui** [comment]
@k06a Sort of, see #21 for details
