### ISSUE TITLE
Simple loading NSProgressIndicator on load

### ISSUE THREAD

**Issue by SunburstEnzo** [insidegui/WWDC#20]
I opened the app and for 5 minutes it was just blank but eventually it loaded the content. For a better ux it is probably worth adding some kind of progress notifier.

Also, Check for Updates would be great for the release versions :D

**Comment by insidegui** [comment]
Yeap.

**Comment by art-divin** [comment]
I would rather create a separate issue for "Check for Updates" thingy :wink:
#31
