### ISSUE TITLE
Menu command to toggle sidebar only works for the first tab you use it in

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#201]
Title is self-explanatory.

**Comment by BNTR** [comment]
@insidegui  You sure about 'Vidoes' tab? I reproduced it on 'Shedule' tab when tap 'View/Hide sidebar' and still see side bar.

**Comment by insidegui** [comment]
You are correct, the title of the issue is not very clear. The toggle command will work on the first tab you use it and then it will not work in the other.

**Comment by bcmn** [comment]
This is irrelevant after #290.
