### ISSUE TITLE
Sometimes videos are duplicated on launch and the app freezes

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#205]
Sometimes if the app was quit while on the videos tab, when launching it again it will go into a weird state where videos appear duplicated multiple times and the app is frozen for a few seconds.

![screen shot 2017-05-30 at 20 22 59](https://cloud.githubusercontent.com/assets/67184/26609122/cb4f1932-4575-11e7-93ff-63e8f6dba351.png)

**Comment by makoni** [comment]
For me the app freezes forever =(

**Comment by davejewell** [comment]
This is happening for me too.  UI is unresponsive - I see multiple copies of WWDC 2017 - Session 102 in the sidebar.   Tried force-quitting and installing 5.0.8 - same result.  Activity monitor shows zero network activity for the app, but it's using lots of CPU.  Was working great until yesterday.  :-(  
![dead-wwdc](https://user-images.githubusercontent.com/823898/27011595-8f329a60-4eb6-11e7-9f21-e1dac32a48a2.png)

**Comment by onato** [comment]
It happened to me too. I was just really patient and switched to the Schedule tab, quit and restarted. It was then fine, however, it happens again if I quite whilst on the videos tab.

**Comment by davejewell** [comment]
Yes - you're right.  Switching to Schedule before quitting seems to be a good work-around.

**Comment by objectivechris** [comment]
I can't even click on the Schedule tab.

**Comment by davejewell** [comment]
As "onato" mentioned, you have to be VERY patient.  Last night, I sat there five mins or more with the beachball spinning on WWDC.  Eventually it woke up and smelled the coffee  :-)

**Comment by insidegui** [comment]
Fixed in e1d6d510dcd205f2b4c51b0179f7ce681c026f33

[Released in 5.1](https://github.com/insidegui/WWDC/releases/tag/5.1)

**Comment by davejewell** [comment]
Brill - thanks for the fix.  👍
