### ISSUE TITLE
Implement playlists

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#206]
The new version of the iOS app has playlists with curated sessions. We could add a new tab to the app called "Featured" that would contain these playlists.

**Comment by insidegui** [comment]
Other sections that should appear above the curated playlists:

Favorites:
Sessions recently added to favorites, most recently added first

Downloaded:
Recently downloaded sessions, most recently downloaded first

Bookmarked:
Sessions with recently created bookmarks, most recently bookmarked first

**Comment by insidegui** [comment]
During WWDC there should also be a section for currently live sessions and "up next" when there are no sessions live, this should be a separate task added to the 2018 milestone.

**Comment by insidegui** [comment]
Almost made it to 6.0, but some outstanding issues prevented us from shipping. Will be there on 6.1, probably alongside #376.

**Comment by bcmn** [comment]
Addressed in #439.
