### ISSUE TITLE
Sidebar contextual menu

### ISSUE THREAD

**Issue by VicenteBorrell** [insidegui/WWDC#216]
Is there a way to mark as unwatched?
I think it could be done by right clicking on the session/video cell and selecting from a menu.
There could also be other options in the same menu like:
- Download / Delete download
- Mark as favorite / Remove from favorites
- Share

What do you think @insidegui ?

**Comment by insidegui** [comment]
Yes, I renamed this to "Sidebar contextual menu". In v4 you could select multiple sessions on the sidebar and use the contextual menu for these kinds of actions, it's not available yet because I didn't have time to implement it.

**Comment by VicenteBorrell** [comment]
OK!

**Comment by insidegui** [comment]
Another action that must be available in the contextual menu: #223

**Comment by insidegui** [comment]
Implemented by @SoneeJohn in #246
