### ISSUE TITLE
Add ability to mark a video as watched.

### ISSUE THREAD

**Issue by lemonkey** [insidegui/WWDC#223]
This will allow favorited videos to be filtered out if you've already watched them.

The older version of the app did this...

**Comment by insidegui** [comment]
Thanks, we're discussing the contextual menu in #216

**Comment by insidegui** [comment]
I'll close this since this feature will be implemented as part of #216

**Comment by lemonkey** [comment]
Thanks, just got the update and it works great. 
👍
