### ISSUE TITLE
Applying filters hides session date/time information

### ISSUE THREAD

**Issue by joshfriend** [insidegui/WWDC#226]
For those of us not at WWDC, seeing labs in the list is not useful, so the option to filter them out is great. However, filtering to just sessions hides all session date/time information so you can't tell when a session is going to happen. The nice section headers that group similar session times also disappear.

**Comment by IanHoar** [comment]
Came here to report this as well. Would like to be able to see the session times when filtering favourites.

**Comment by adamcleavey** [comment]
+1

**Comment by joshfriend** [comment]
I think stalebot is a poor addition to a repo like this that is active mostly at one week per year

**Comment by insidegui** [comment]
We accept pull requests :)

**Comment by bcmn** [comment]
Worth noting that as of #325 this has been partially addressed, as day and time of session is now displayed for . 

However, we haven't addressed the section header aspect of this. Currently they're excluded while filters for complexity reasons.
