### ISSUE TITLE
Searching prevents spaces

### ISSUE THREAD

**Issue by DevanB** [insidegui/WWDC#227]
I was perusing the Schedule tab today and needed to search for "Design Studio Shorts". To my surprise, I found that the search is preventing spaces. I'm assuming this is a bug, but I could be wrong. I wish I knew more about macOS app development because I'd love to detail where the problem may be and submit a PR.

Thanks for the app!

**Comment by insidegui** [comment]
This happens when the player is active because it "swallows" all space key presses 😬

Will fix. Thanks

**Comment by bcmn** [comment]
Seemingly fixed in #387 & #478.
