### ISSUE TITLE
Enable scrolling of summary text

### ISSUE THREAD

**Issue by SoneeJohn** [insidegui/WWDC#233]
The summary text sometimes doesn't show all the text.

![screen shot 2017-06-08 at 3 16 25 pm](https://user-images.githubusercontent.com/4827301/26946517-97b35b4e-4c5d-11e7-9c0c-1a651344f085.png)

**Comment by davedelong** [comment]
As an observation, the `SessionSummaryViewController` limits that label's `maximumNumberOfLines` to 5.

However, this session has the longest summaries of all sessions. By setting the `maximumNumberOfLines`  to `0`, we get the following layout. I think this is a far simpler and more straight-forward solution than trying to make it scroll.
<img width="1172" alt="screen shot 2018-05-27 at 6 41 35 pm" src="https://user-images.githubusercontent.com/112699/40592524-bedb1022-61dd-11e8-8509-8fc66828615e.png">

**Comment by insidegui** [comment]
Me and @davedelong talked and we decided to add a reasonably large limit to the number of lines just to prevent the layout from breaking completely in case there's a session with a huge description. I agree that implementing scrolling would be overkill given the average length of descriptions.
