### ISSUE TITLE
App freezes on launch

### ISSUE THREAD

**Issue by persimmonsoft** [insidegui/WWDC#237]
It worked for quite a few launches. I have now downloaded a number of the videos, but now it freezes on launch.
Here is the sample:

[Sample of WWDC.txt](https://github.com/insidegui/WWDC/files/1062753/Sample.of.WWDC.txt)

**Comment by insidegui** [comment]
Are you sure this is not a duplicate of #205 ?

**Comment by persimmonsoft** [comment]
You are correct, this looks to be a duplicate of #205
