### ISSUE TITLE
Crash during playback

### ISSUE THREAD

**Issue by jshier** [insidegui/WWDC#238]
I'm currently watching the "Debugging in Xcode 9" and the 5.0.7 has crashed twice now after a few minutes of playback. 5.0.6 was stable yesterday, despite the lack of energy assertions.

[WWDC Crashes.zip](https://github.com/insidegui/WWDC/files/1062943/WWDC.Crashes.zip)

**Comment by insidegui** [comment]
This is fixed in 5.0.8. Sorry about that.
