### ISSUE TITLE
Version update only functions in Applications folder...

### ISSUE THREAD

**Issue by jshier** [insidegui/WWDC#239]
In 5.0.3 to 5.0.7, attempting to update the app will fail unless it's running the `/Applications` folder, and only that folder. The error presented is the typical Sparkle error about running from a disk image, which I'm certainly not doing.

**Comment by insidegui** [comment]
Can you give me the exact error message shown by Sparkle?

**Comment by jshier** [comment]
```
WWDC can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move WWDC to your Applications folder, relaunch it from there, and try again.
```
Oddly, it only occurs after the application is unzipped and I'm running it out of the Download folder. If I move it to the Applications folder it updates fine, and if I move it back to the Downloads folder again it updates fine as well.

**Comment by insidegui** [comment]
Hmmm, looks like it's a known issue in Sparkle. I don't think there's much I can do here...

**Comment by insidegui** [comment]
I'll close this for now because I don't know where to go from here. If you happen to find a possible solution please answer and reopen the issue. Thanks!
