### ISSUE TITLE
The WWDC app is not starting now.

### ISSUE THREAD

**Issue by afixibiranchi** [insidegui/WWDC#247]
The app was working fine and i was able to view and download wwdc 2017 session videos.
But its not starting now.
I am running Mac OS Sierra Ver 10.12.5

**Comment by insidegui** [comment]
What do you mean by "not starting"?
Does it crash?
If it crashes, does it produce a crash log?
Is there an error message on the screen?
Does it just hang? If it hangs, this is probably a duplicate of #205.

**Comment by insidegui** [comment]
I'll close this as invalid. If you have more info please reopen it.

Thanks
