### ISSUE TITLE
Small issue with context menu 

### ISSUE THREAD

**Issue by SoneeJohn** [insidegui/WWDC#249]
The context menu should disable the download menuItem in this instance.

See https://github.com/insidegui/WWDC/blob/ee4b19a2cfb13b0f3194081ad7c2d559e0faffef/WWDC/SessionsTableViewController.swift#L402

Should also consider if the `DownloadManager` returns `true` for `isDownloading`

![screen shot 2017-06-12 at 9 43 28 am](https://user-images.githubusercontent.com/4827301/27036691-afa63728-4f53-11e7-9324-e0f97faf00cc.png)

**Comment by insidegui** [comment]
This will go on the next release, forgot to merge it for 5.1 😬
