### ISSUE TITLE
2x or greater speedup has no sound

### ISSUE THREAD

**Issue by klundberg** [insidegui/WWDC#25]
If you try to stream a video at 2x speed or greater, there's no sound at all. I haven't tried downloading a video before watching yet to see if that's different, but even if it is it'd be nice to watch videos at 2x speed and hear what's being said without needing to download them.

**Comment by insidegui** [comment]
I don't own the video decoding/streaming stack, that's on Apple :/

**Comment by klundberg** [comment]
Aha, i see. That's unfortunate :(. I'll close this then, thanks for the reply!
