### ISSUE TITLE
Download Manager

### ISSUE THREAD

**Issue by adrum** [insidegui/WWDC#251]
It would be nice to be able to see a list of all the videos currently being downloaded with each of their progress. It is a little painful to click between videos to see the progress of downloads currently. Something as simple as Safari's download manager would be really helpful.

![example](https://user-images.githubusercontent.com/1464185/27054766-17579880-4f90-11e7-9d9a-b5644a40472e.png)

**Comment by insidegui** [comment]
We're working on it, I converted the project task to an issue so it's easier to refer to: #252 

Thanks
