### ISSUE TITLE
Did app auto-update, now it just hangs at startup.

### ISSUE THREAD

**Issue by barrettj** [insidegui/WWDC#255]
### Before opening you issue, make sure you answer YES to all of the questions below.

- Are you running the latest version of the app?
Yes, it just Auto Updated
- Are you running a release, stable version of macOS?
Yes
- Have you looked at previous issues to see if you're having an issue that's already being worked on?
Yes, but it looks like you thought you had it solved
- If your issue is about compilation, project setup, have you followed the instructions from the readme?
NA

### If you answered YES to all of the questions, please provide as much information as possible about your issue

- Version of macOS - Latest, 10.12.5
- Version of the app - Latest, just did an auto update
- What were you trying to do when the issue happened
App did an auto update, now just hangs on start
- Any particular hardware/software configuration you have that might be affecting the app
I did the auto update of the app
- If it is a hang (beach ball), please provide a process sample
[Sample of WWDC.txt](https://github.com/insidegui/WWDC/files/1080884/Sample.of.WWDC.txt)

- If it is a wrong behavior, list all steps required to reproduce it
Just launch the app
- Please add screenshots if you think they might help us diagnose the issue

**Comment by insidegui** [comment]
Go to `~/Library/Application Support/io.wwdc.app`, zip that entire folder and send it to me. If you want to send it privately you can use wetransfer and send it to `eu [at] guilhermerambo.me`.

**Comment by barrettj** [comment]
Should I quit the app before zipping, or leave it running?

**Comment by insidegui** [comment]
Force quit it before zipping the folder.

**Comment by barrettj** [comment]
One of the files in there is 9.6GB (ConfCore.realm)

**Comment by insidegui** [comment]
Oh, that's an issue 😅

**Comment by barrettj** [comment]
[EverythingButConfCoredotrealm.zip](https://github.com/insidegui/WWDC/files/1080913/EverythingButConfCoredotrealm.zip)

**Comment by insidegui** [comment]
Sorry, ConfCore.realm is the main database file and that's where the problem is. But I understand you can't upload a ~10gb file 😥

We're still investigating.

**Comment by barrettj** [comment]
Would I be safe to rename that folder to io.wwdc.app.old-faulty and try running the app - I don't have any preferences of any importance.  I could then also try switching back to that version if theres a future update to see if it fixes things.

When I'm not at work I can try uploading it over the weekend (work internet is too slow and I'd have to leave before it got done)

**Comment by insidegui** [comment]
Yes, it is safe to rename the folder and run the app. It will then re-download and parse all of the data. 

Version 5.1.1 should have fixed it tho, although we're still not quite sure what is causing this issue for some people and not others.

I don't think there's a lot we can do with that huge DB file, I have another sample from @bcmn which should be enough to try and diagnose this once again.

**Comment by insidegui** [comment]
@barrettj [Version 5.1.2](https://github.com/insidegui/WWDC/releases/tag/5.1.2) is out, can you try it out and check if it behaves?

**Comment by JohnCoates** [comment]
I was having ~3 minute hangs on startup before this update, and 5.1.2 fixed this for me.
