### ISSUE TITLE
App v5.1.1 is not stable

### ISSUE THREAD

**Issue by afixibiranchi** [insidegui/WWDC#256]
![screen shot 2017-06-16 at 11 29 32 pm](https://user-images.githubusercontent.com/191425/27233395-df0e91d6-52eb-11e7-9932-cef8749168eb.png)

Still not able to run the latest ver:5.1.1

**Comment by insidegui** [comment]
Duplicate of #255 ?

**Comment by insidegui** [comment]
Closed as duplicate of #255
