### ISSUE TITLE
Clear Download State

### ISSUE THREAD

**Issue by Blackjacx** [insidegui/WWDC#257]
macOS Sierra 10.12.5
WWDC 5.1.1

I deleted the files from the Finder in the ~/Library/Application\ Support/WWDC folder. All the previously downloaded session videos remain being marked as downloaded. Where do you store the download state of the sessions so I can manually resolve this issue? Better would be to offer a "clear downloads"-button of course.

Cheers 
Stefan

**Comment by insidegui** [comment]
The download flag should've been cleared when you deleted the files. This is definitely a bug.

Do you remember whether the app was opened when you deleted the files?

**Comment by Blackjacx** [comment]
Yep it was opened!

**Comment by insidegui** [comment]
Thanks. This will be fixed on the next release.

**Comment by insidegui** [comment]
@bcmn When the DownloadManager starts, it needs to iterate through all sessions which have the `isDownloaded` flag set to `true` and check if the file still exists on disk. To know where to find the file you use the `relativeLocalURL` from the `SessionAsset` of type `hdVideo`.
