### ISSUE TITLE
Add "Reveal in Finder" context menu

### ISSUE THREAD

**Issue by adamsimo** [insidegui/WWDC#258]
Please add item "Reveal in Finder" to the context menu to reveal a video file in the Finder.

![2017-06-21_11-39-10](https://user-images.githubusercontent.com/20772588/27378112-2581e3dc-5677-11e7-9131-5a9cebde7f08.png)

**Comment by insidegui** [comment]
Will do.

**Comment by adamsimo** [comment]
thanks
