### ISSUE TITLE
Download slides next to the video files

### ISSUE THREAD

**Issue by adamsimo** [insidegui/WWDC#259]
Please enable downloading slides next to the video files to match the following pattern:

102_hd_platforms_state_of_the_union.mp4
102_platforms_state_of_the_union.pdf
110_convenience_for_you_is_independence_for_me.pdf
110_hd_convenience_for_you_is_independence_for_me.mp4
207_hd_whats_new_in_cocoa.mp4
207_whats_new_in_cocoa.pdf
208_hd_natural_language_processing_and_your_apps.mp4
208_natural_language_processing_and_your_apps.pdf
210_hd_whats_new_in_core_data.mp4
210_whats_new_in_core_data.pdf
211_hd_touch_bar_fundamentals.mp4
211_touch_bar_fundamentals.pdf

**Comment by insidegui** [comment]
We had this feature on v4, not exactly like this but we had a builtin PDF viewer. I don't believe this is worth implementing and maintaining, but I'll leave this opened so others can say if they want this as well.

If we do implement it, I don't believe downloading them with the videos would be a good idea.

**Comment by adamsimo** [comment]
I understand there is no need to implement built-in PDF viewer, but it would be nice to have a button that opens the slides in system default PDF viewer without need to go to the Finder and to hunt for the PDF file ;)

**Comment by bcmn** [comment]
There's not been any further discussion, & the current behaviour allows accessing & manual downloading of slides very easily, so we'll close this issue for now.
