### ISSUE TITLE
Missing Video Length on The Preview/Details Screen

### ISSUE THREAD

**Issue by Blackjacx** [insidegui/WWDC#262]
macOS Sierra 10.12.5
WWDC 5.1.1

When I select a video session on on the left, I recognized that I miss the video length on the right side at the bottom where you paced wwdc year, session number and platforms. I always must press play to see the time. 

This would be a valuable and I think easy enhancement :-)

**Comment by insidegui** [comment]
Definitely.

**Comment by VicenteBorrell** [comment]
Yeah, I thought about it recently too. Thanks for bringing it up @Blackjacx 
Is the video length available in the metadata @insidegui ?
I think it would be nice to even show it on the sidebar :)

**Comment by insidegui** [comment]
@VicenteBorrell It wasn't before, with the changes this year it is now available :)

**Comment by Blackjacx** [comment]
I'm looking forward ;)
