### ISSUE TITLE
Add ability to mark videos as favorite/bookmarked

### ISSUE THREAD

**Issue by klundberg** [insidegui/WWDC#27]
It'd be nice to mark favorite videos as such, to have a short list of videos that may be useful in the future to refer back to, similar to how the wwdc app on iOS lets you favorite sessions to keep track of them for the conference.

**Comment by insidegui** [comment]
I am actually trying to make use of the same favorites from the iOS app, if I can't accomplish that I will make a separate favorites system.

**Comment by brennanMKE** [comment]
@insidegui How are you able to access these favorites? Is there an API you can access once the user is authenticated? How do you authenticate the user?

**Comment by brennanMKE** [comment]
btw, I am interested working on one of these issues to learn a bit more about Mac development after doing only iOS work. Let me know where you'd like help. I can fork and send PRs.

**Comment by insidegui** [comment]
I sniffed the traffic from the iOS app and there is an authentication happening, after the developer logs in there are 3 HTTP calls which can be made:
1 - Mark a video as favorite
2 - Remove a video from favorites
3 - Get a list of all favorites

Once we have the auth working, the rest is simple. I didn't look too much into It yet, but if you are comfortable with reverse engineering I would love to have some help :)

**Comment by brennanMKE** [comment]
I use the Paw HTTP Client which is really helpful at this sort of thing. If you can provide me with URLs I could try them out and see what I can do with them. Is this not using SSL? How could you sniff the traffic? Just URLs?

**Comment by insidegui** [comment]
It uses SSL. I use Burp Suite, It can generate SSL certs on the fly so you can sniff https traffic, but for this to work I've had to install a custom profile on my iOS device, and It doesn't work with all applications. The best approach would be to actually reverse engineer the app and see what kind of auth mechanism is in place, but for that the device has to be jailbroken.

**Comment by brennanMKE** [comment]
Oh, I never jailbreak my iOS devices. But if you can tell me which REST calls are needed I could write the code for it.

**Comment by insidegui** [comment]
The REST calls are the least of our problems, I still have to figure out how the authentication works :(

**Comment by brennanMKE** [comment]
Maybe it is not worth the effort just to manage favorites. It could easily be done with a service like Parse. And CocoaPods Keys could be used to securely hold onto the keys and build the app with Parse support. Once the data is stored in Parse and the user is able to connect an identity with Parse their list of favorites could also be made available in a web browser or iOS app. Then it would be possible to also store bookmarks at different points in a presentation and also store notes. I would find that useful.

https://github.com/orta/cocoapods-keys

**Comment by insidegui** [comment]
There will be no iOS app, so I don't see a need to have a service for the favorites. If I can't work out how to integrate with the native iOS WWDC app I'll implement something way simpler with NSUserDefaults ;)

**Comment by brennanMKE** [comment]
Syncing with iCloud could also be a service which does this work without requiring keys for a third-party cloud service.

I do have an old iPhone 5 at home. Maybe I could use that for reverse engineering the authentication scheme, but the implementation could change anytime. It would be nice if Apple provided a supported service but that would be dreaming.

**Comment by insidegui** [comment]
iCloud is only available for apps distributed via the AppStore :/

**Comment by brennanMKE** [comment]
My take is that favorites is not as useful as bookmarks and notes which can pinpoint an exact position in a presentation. Since Apple's app does not do that this is a feature which makes this app more useful to developers.

Keeping the focus on notes and bookmarks is probably more worthwhile.
