### ISSUE TITLE
2017 video transcripts inaccessible from the application 

### ISSUE THREAD

**Issue by bcmn** [insidegui/WWDC#271]
It is currently not possible to access transcripts of any 2017 session when using the application, though they are now available on developer.apple.com.

We're aware of this, & are actively working on plans to fix this for both 2017 sessions, as well as ensuring timely access to transcriptions for future years is further under our control.

**Comment by insidegui** [comment]
@bcmn I pinned this one, I know it's one of your favorites 😜

**Comment by insidegui** [comment]
There's been some development on this issue: the creator of ASCIIWWDC has asked us if we'd like to run the service since he's unable to maintain it at the moment. We are probably going to maintain ASCIIWWDC going forward and fix the missing transcripts issue.

**Comment by bcmn** [comment]
Addressed in #467.
