### ISSUE TITLE
Replace SwiftyJSON with JSONX

### ISSUE THREAD

**Issue by MKGitHub** [insidegui/WWDC#276]
Replace SwiftyJSON with JSONX (https://github.com/MKGitHub/JSONX)
JSONX is lighter gives lower memory consumption and incredible performance :-)

or, should send a PR?

**Comment by insidegui** [comment]
I'm not interested in changing the JSON parsing at the moment. We'll probably move to Swift 4's `Codable` as soon as it's stable. Thanks for the suggestion tho.

**Comment by MKGitHub** [comment]
Swift 4's Codable will make the code more complex and add a lot of boilerplate – but ehh ok! 🤦‍♂️
