### ISSUE TITLE
Older WWDC content not available

### ISSUE THREAD

**Issue by rob-nash** [insidegui/WWDC#279]
The newer version of the App shows content as old as WWDC 2013. The older version of the App shows content as old as WWDC 2012.

Why the difference in content? And what about the older WWDC content?

**Comment by insidegui** [comment]
The app grabs the data directly from Apple's API, which currently only returns videos starting from 2013.

**Comment by rob-nash** [comment]
I removed the new version of the App. I installed the old version of the App. The old version still shows content as old as 2012.

I appreciate content older than 2012 might not be available in the API but it seems strange that 2012 doesn't show in new App, when it does in the old.

Try installing the old App and take a look.

**Comment by rob-nash** [comment]
Maybe I have cached content on my hard disk?

**Comment by insidegui** [comment]
The old version uses a different API which only shows content up to 2016. Apple changes the API every year. Check the iOS app: it doesn't show content from 2012. Since we use the same API as their iOS app, we don't either.

**Comment by rob-nash** [comment]
<Thumbs Up>

**Comment by mediter** [comment]
But on the website of another project of yours, namely ASCIIwwdc, it lists transcripts for videos dating as far back as 2010. Is it possible to use a separate data source for videos released between 2010 and 2013?

**Comment by insidegui** [comment]
That's not something we're interested in doing.
