### ISSUE TITLE
[Suggestion] Add a small Text field for personalized summary

### ISSUE THREAD

**Issue by sohaeb** [insidegui/WWDC#280]
Say I watched "What's new in store kit" session that was talking about in-app purchases. In the future, if I want to go back and re-watch the session that talk about in-app purchases. I have to go through many videos as the title doesn't really say much about the details session. or even start reading description of each video. 

Other examples:

- "ignore this session" comment since i'm not really interested in Device config & management for schools
- "watch this later to learn more about Pinpoints in maps" comment
- Nothing new in this session
- Nothing important here

For now i'm using a google doc has these notes/summaries
So I was thinking if it would be a good idea to have this directly in the wwdc app instead of a separate note 

Quick edit of my suggestion:

![artboard](https://user-images.githubusercontent.com/2378086/28998054-234854c4-79f0-11e7-8008-2f6b4fbdcd3d.png)

**Comment by insidegui** [comment]
As for the "ignore this session" thing, I usually mark the sessions I don't care about as watched even though I haven't watched them and I try to mark all interesting sessions as favorites.

To add custom metadata to sessions, have you tried the bookmarks feature?
