### ISSUE TITLE
Unintended scroll when switching tabs 

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#305]
I believe this is a side effect of #294.

When the app is first launched, it takes a while for the selection to be restored and the restoration is animated, which can confuse the user if the user scrolls before the restoration occurs.

Another issue is when switching tabs: if I have a saved selection for the schedule tab, it will be restored when coming back from the videos tab, destroying my scroll position. The restoration should only occur on app launch.

![scrollreset](https://user-images.githubusercontent.com/67184/30084624-8714ebf2-9269-11e7-9136-19164259424b.gif)

**Comment by insidegui** [comment]
@VicenteBorrell Do you agree that the behavior shown in the gif is bad UX?

**Comment by allenhumphreys** [comment]
Introduced in #294, it was definitely unintentional. I meant for it to scroll during an update to search results that are triggered by a user, though I was unsure whether that was even desired.
