### ISSUE TITLE
Session list disappears

### ISSUE THREAD

**Issue by otaviolima** [insidegui/WWDC#306]
Using 5.1.3

1. Do a search
2. Close the app
3. Open back
4. Clear search

Expected behavior:
List of sessions 

Current behavior:
Empty list.

Workaround:
Toggling filter button makes the list appear again.

**Comment by insidegui** [comment]
Is this in the current release version or master?

**Comment by otaviolima** [comment]
I tested on release, once I get home I will test against master.

**Comment by otaviolima** [comment]
Can't reproduce using master.
