### ISSUE TITLE
App icon shading rendered incorrectly on macOS High Sierra

### ISSUE THREAD

**Issue by bcmn** [insidegui/WWDC#311]
<img width="102" alt="screen shot 2017-09-09 at 10 48 02" src="https://user-images.githubusercontent.com/11646957/30239209-2d1a938e-954f-11e7-88c5-31d87ee4252e.png">

The app icon renders in the dock & Finder with a lighter, "whitewashed" appearance on some devices running the macOS 10.13 beta. I think Gui & I initially assumed this was an OS issue that would be resolved, but seeing as it's persisted throughout betas & we're rapidly approaching the release of the OS its worth looking into whether we've made any colour profile or similar oversights.

My device is a 2016 MBP (13, 2). I contacted someone running 10.13 on an older MBP (11, 3), & they didn't appear to be having the same issue.

I found [similar reports for a handful other applications](https://github.com/atom/atom/issues/15410), but I struggled to recreate these now on my device, so they may have made an alteration without describing it in their issue tracking.

**Comment by allenhumphreys** [comment]
Is there any chance an early beta created an incorrectly rendered version of the icon and cached it? I'm thinking this because of what you said about not being able reproduce other apps.

I know that you can pin an app to the dock and then delete the app and the icon will remain, so the system must do something to keep the image around.

**Comment by bcmn** [comment]
@allenhumphreys In verifying the issue, I have completely removed the application & run a number of commands intended to outright delete the icon caches.

`sudo find /private/var/folders/ -name com.apple.dock.iconcache -exec rm {} \;
sudo find /private/var/folders/ -name com.apple.iconservices -exec rm -rf {} \;
sudo mv /Library/Caches/com.apple.iconservices.store com.apple.ic`

I have also replaced the icon for the app with the folder icon, & ensured this had replaced the icon in all dock & finder references to the app, before removing the alternate icon, reverting back to the one in the bundle.

The issue persisted.

**Comment by allenhumphreys** [comment]
That's some good background!

**Comment by insidegui** [comment]
I think the icon that's in the app came pre-rendered from Raphael, maybe it's some sort of colorspace issue?

**Comment by VicenteBorrell** [comment]
Other devs having the same problem:
https://twitter.com/maxvoltar/status/907079810437885953
In this case Abstract, which is not native, but there are native cases in the comments.

**Comment by LGriffioen** [comment]
I've been looking into this all morning. As far as I can tell, it appears to affect any image that has no color profile?

![screen shot 2017-09-11 at 3 07 18 pm](https://user-images.githubusercontent.com/1846960/30292219-589e7b28-9703-11e7-8552-e3e98f3eef81.png)

Source image: (renders properly in-browser on 10.12, but not on 10.13)

![washedout](https://user-images.githubusercontent.com/1846960/30292249-6c04c906-9703-11e7-9a72-0af612d820e6.png)

**Comment by maxvoltar** [comment]
Did some research, and apparently `.icns` files generated with Icon Slate.app are the culprit here. Really funny that this impacted mostly Electron apps, as their designers don't use Xcode to generate their app icons.

Started using Icon Creator, and the icon looks great now.

**Comment by insidegui** [comment]
I asked the designer to provide the original assets so I can recreate the icon and fix this issue.

**Comment by LGriffioen** [comment]
It looks like you can fix images that are missing color profiles by using Preview. Just open the image, and choose Tools > Assign Profile... and pick something that works well for your image (I used sRGB). Important note: **this will only work on 10.12 and earlier**. If you do the same steps on 10.13, the washed out color is burned in and the image is permanently ruined.
