### ISSUE TITLE
App not working at all on macOS sierra.

### ISSUE THREAD

**Issue by CosmicYogi** [insidegui/WWDC#317]
est stable release of WWDC from wwdc.io but I am not able to do anything I mean the app is completely blank and Activity indicator is there forever.
I had attached the relevant screenshots.

<img width="1440" alt="screen shot 2017-09-19 at 9 14 32 am" src="https://user-images.githubusercontent.com/7416058/30575069-d77e1caa-9d1b-11e7-82c5-11e23e35f128.png">
<img width="587" alt="screen shot 2017-09-19 at 9 18 44 am" src="https://user-images.githubusercontent.com/7416058/30575070-d7df21b2-9d1b-11e7-9610-a93559dbcffe.png">

**Comment by insidegui** [comment]
Did you see a spinning beachball (hang) or is it working but just not showing any data?

**Comment by CosmicYogi** [comment]
Actually, It did not hang it was just not showing any data and it was crashing again and again and the same problem was occurring but I don't know how but it started working unpredictably.
I mean I was not able to get any info why it happened in the first place.
<img width="1440" alt="screen shot 2017-09-20 at 8 59 40 am" src="https://user-images.githubusercontent.com/7416058/30625709-6c405562-9de2-11e7-85fc-c9d19c696d37.png">
