### ISSUE TITLE
setDisplayedRows calls UI method from a background queue

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#318]
The `setDisplayRows` method in `SessionsTableViewController.swift` calls `tableView.selectedRowIndexes` from a background queue. Although this might not be causing any issues currently, it could result in weird behavior and/or random crashes.

https://github.com/insidegui/WWDC/blob/d69676e63924ce47195850bde821d8471c97a697/WWDC/SessionsTableViewController.swift#L83

**Comment by antonselyanin** [comment]
I moved this call to the main thread in #322 PR because unit tests were crashing.

**Comment by insidegui** [comment]
#322 disabled main thread checking so the tests would run. When this issue gets fixed, we should re-enable the main thread checker for tests.
