### ISSUE TITLE
How to select 1080P or 720P version？

### ISSUE THREAD

**Issue by wellcheng** [insidegui/WWDC#327]
First，I can not find a entrance to select the up two option。
Second，I think this is auto selection，but when I cached long videos，there also lower version

**Comment by insidegui** [comment]
When streaming, the system will automatically select the best quality for the window size and network speed. When downloading, there's only one quality available. This is a limitation of Apple's streaming service we unfortunately can't work around.

**Comment by Chidorin** [comment]
on 1280x1024 displays it chooses the worst quality, may be if there was an ability to hide left and bottom menus to make video fill the whole window and trigger higher resolution

**Comment by insidegui** [comment]
I suggest watching in full screen. Just double click the video. If you need it in a resizable window over other content, use Picture in Picture.
