### ISSUE TITLE
Old database versions for migration tests

### ISSUE THREAD

**Issue by antonselyanin** [insidegui/WWDC#329]
I could write some unit tests for `Storage` class, I wanted to start with the migration logic.
Do you have realm files with old database schemas? 

In case you don't have old databases. How do you think, would "reversing" the schemas from the migration code be sufficient for unit tests?

**Comment by bcmn** [comment]
Migration tests seem like a good idea --even if we're a little late to the game on this one.

I don't know if others have old databases they use, but its worth noting that the last V4 release is still available [here](https://github.com/insidegui/WWDC/releases/tag/4.3.1). There's no need for reverse engineering the structure from the code we're going to be testing, and doing so seems like it'd only serve to defeat the purposes of the unit test by perpetuating any wrong assumptions. 🤔

**Comment by insidegui** [comment]
Well, we do have some cases (#284 ) where the migration seems to be causing problems. If we could isolate that with unit tests maybe it could help with the solution. @antonselyanin Please send me your e-mail so I can invite you to our Slack.

**Comment by insidegui** [comment]
Do we still think this is important/useful?

It's been almost a year since the 5.0 update, I feel like we should plan on removing the migration code altogether at some point.

**Comment by bcmn** [comment]
Yeah, I think it’d be perfectly reasonable to remove the migration code with 6.0. Though I feel we should still try to make it a principle of the project to test any (presumably smaller) schema migrations in future.

**Comment by ChinaHackers** [comment]
The macOS 10.12.6 WWDC5.3 version prompt does not respond.
Why does it happen?

**Comment by insidegui** [comment]
@ChinaHackers Please [open a new issue](https://github.com/insidegui/WWDC/issues/new). Thanks!

**Comment by ChinaHackers** [comment]
OK!

**Comment by ChinaHackers** [comment]
@insidegui OK.
