### ISSUE TITLE
On first run, no videos are displayed in the "Schedule" tab

### ISSUE THREAD

**Issue by bcmn** [insidegui/WWDC#340]
guard session.year == Calendar.current.component(.year, from: Date()) else {
            return .error(.invalidData)
        }

Due to this guard, at `SessionInstancesJSONAdapter.swift`, line 34, the first run download & parsing of JSON assumes that all "current" WWDC sessions should share the current year of the system calendar. Unfortunately, this doesn't _quite_ work in the pre-WWDC, January-through-June 2018 period. 😛 As such, no videos are displayed in the Schedule tab if the app was first installed during this period.

**Comment by insidegui** [comment]
This was fixed by #369
