### ISSUE TITLE
The macOS 10.12.6 WWDC5.3 version prompt does not respond. Why does it happen?

### ISSUE THREAD

**Issue by ChinaHackers** [insidegui/WWDC#370]
- Version of macOS : 10.12.6
- Version of the app: 5.3

The macOS 10.12.6 WWDC5.3 version prompt does not respond.
Why does it happen?

### Please reply to how to solve this problem.

**Comment by insidegui** [comment]
@ChinaHackers Hi! Can you please describe your problem in more detail? Thank you!

**Comment by ChinaHackers** [comment]
@insidegui Open the WWDC mouse to be a busy state ----> wind fire wheel.

**Comment by insidegui** [comment]
@ChinaHackers Can you try version 6 and see if you still have the same issue? Thanks

**Comment by ChinaHackers** [comment]
@insidegui   I tried it a few hours ago. It's the same bug.. Do you want to upgrade High Sierra?

**Comment by insidegui** [comment]
I'm closing this as a duplicate of #464, look for updates there.
