### ISSUE TITLE
Display "News"

### ISSUE THREAD

**Issue by bcmn** [insidegui/WWDC#375]
Similar to #331 & #206, the last version of the API included "news". We intend to support this & display it in it's own tab.

**Comment by bcmn** [comment]
As far as I know, that's the plan. In my experience (as a non-attendee), the same has always been true of the official app, right? You can sign in, but I still see news that seems focused at attendees only?

**Comment by davedelong** [comment]
If you can sign in, that means you're an attendee. This is what the "accessLevel" stuff in `news.json` is about: https://github.com/insidegui/WWDC/blob/master/Fixtures/json/news.json#L10

**Comment by insidegui** [comment]
I think we should just skip this feature altogether. I'm not sure how useful it would be and it would be quite a bit of work to get it working. Besides, there's the issue of not knowing if the user is an attendee or not and Apple could get upset if we displayed all info (even for non-attendees). What do you think @bcmn, @allenhumphreys ?

**Comment by davedelong** [comment]
What about checking for the presence of the attendee ticket in Wallet? They're located in `~/Library/Mobile Documents/com~apple~shoebox/UbiquitousCards/`.

**Comment by insidegui** [comment]
That folder doesn't exist on my Mac

**Comment by bcmn** [comment]
I think we can probably close this as “Won’t do”?

**Comment by insidegui** [comment]
Yeap
