### ISSUE TITLE
Implement keyboard shortcut to switch between tabs

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#379]
It's very common in apps that have tabs to be able to navigate between them using ⌘{ and ⌘}. I think we should implement them in the app to switch between tabs like Schedule and Videos.

**Comment by bcmn** [comment]
Does this tie into the larger shortcut revamp we had planned when #230 was still open? It got closed in the Great Stalebot-ening of '17. Or would that be a significantly larger amount of work?

Maybe we could try & document the full list of shortcuts we ultimately want to work towards. 🤔

**Comment by insidegui** [comment]
Yeah I think we could re-introduce that issue and include these new shortcuts. It's not that difficult to implement, we'd have to add menu items for the actions and associated default shortcuts to them (which could be customized using System Preferences).

> the Great Stalebot-ening of '17

That would make for a great dystopian movie

**Comment by davedelong** [comment]
I think these should be `⌘1` and `⌘2`.

`⌘{` and `⌘}` are generally reserved for switching between window tabs.

Adding this should be trivial; just a couple of new menu items in the bar and an `@IBAction` to flip stuff around
