### ISSUE TITLE
Sidebar size saving is broken

### ISSUE THREAD

**Issue by allenhumphreys** [insidegui/WWDC#404]
The side bar is always getting the initial size of 300 even though autosave should be working.

**Comment by davedelong** [comment]
Unless I'm missing something, we're not setting the `autosaveName` on the actual `NSSplitView` used.

**Comment by davedelong** [comment]
Confirmed: it's definitely getting reset when the app re-launches

**Comment by allenhumphreys** [comment]
<img width="780" alt="screen shot 2018-05-31 at 4 05 53 pm" src="https://user-images.githubusercontent.com/8225090/40808391-917d0d8a-64ec-11e8-9b3a-71e597555c0a.png">

The sidebar width will not be restored if this preference is selected.

**Comment by edrozenberg** [comment]
Same issue here. I do have that System Prefs setting enabled, but other apps such as ForkLift for ex., have no problems persisting the sidebar width, even with that setting enabled.

Believe this issue can stay open - there is probably a way to fix this issue in the WWDC app.

**Comment by allenhumphreys** [comment]
@edrozenberg Its possible that those apps are restoring the width manually, I'm planning to ask the appkit guys about it tomorrow if I have time.
