### ISSUE TITLE
When Viewing in Full Screen and Browsing Sessions, Video is Black

### ISSUE THREAD

**Issue by spaz926** [insidegui/WWDC#418]
When viewing a video in Full Screen mode and browsing the available videos or scheduled sessions the video shows only a black screen. I assume this has something to do with the PIP mode the video goes into when you click another session while a video is actively playing.

I'm on the current release of the app (6.0.3) and macOS 10.13.5.

**Comment by insidegui** [comment]
Thank you for reporting

**Comment by allenhumphreys** [comment]
@spaz926 Could you provide a screen capture demonstrating your steps to get into this situation?

**Comment by spaz926** [comment]
https://streamable.com/dvjzx

**Comment by insidegui** [comment]
Thanks for the video. @allenhumphreys I was able to reproduce here following the steps mentioned above.
