### ISSUE TITLE
"contributing" refers to a non-existing "roadmap"

### ISSUE THREAD

**Issue by mackuba** [insidegui/WWDC#420]
The "CONTRIBUTING" doc says that before you work on a new feature, you should look at the "ROADMAP". However, the roadmap seems to have been deleted a while ago :-)

**Comment by insidegui** [comment]
@bcmn Can you update the contribution guidelines?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by insidegui** [comment]
The guidelines have been updated.
