### ISSUE TITLE
Downloads window

### ISSUE THREAD

**Issue by mackuba** [insidegui/WWDC#422]
I really miss the Downloads window from the old version (to which I even submitted some PRs, I think)... I would love to see how many downloads I have started and how they're going, and maybe pause some of them to prioritize the one I want to see right now, instead of having to switch back and forth between session pages to check the circular progress bars there.

If, hypothetically speaking, someone were to send you a PR with this ;) would you be interested? What was the reason for removing it during the redesign? Would it make more sense as a small window as before, accessed from the Window menu, or rather as something inside the main window somewhere?

**Comment by insidegui** [comment]
We didn’t have time to reimplement it for the new version yet, but that’s planned. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AnalyzePlatypus** [comment]
This would be great.

**Comment by VicenteBorrell** [comment]
Let me know if you need the design for this 👍

**Comment by insidegui** [comment]
@VicenteBorrell Yes, please :) I think we could show an icon in the toolbar when there are active downloads and show the list of downloads in a popover or window when that icon is selected.

**Comment by allenhumphreys** [comment]
![41206696-4c1776bc-6d08-11e8-92d6-89bae50ac173](https://user-images.githubusercontent.com/8225090/41206822-33b630be-6cd0-11e8-82ba-c012ef440910.png)

Thanks to @mackuba

**Comment by bcmn** [comment]
Evoking the Safari download manager sounds perfect to me.

**Comment by insidegui** [comment]
> Evoking the Safari download manager sounds perfect to me.

Same.

**Comment by insidegui** [comment]
Having ETA and notifications for completion would be nice.

**Comment by VicenteBorrell** [comment]
Are we going to adopt Dark Mode? Should I follow it? 😊

**Comment by allenhumphreys** [comment]
Work began [here](https://github.com/insidegui/WWDC/pull/497)
