### ISSUE TITLE
With Mohave, we should have `NSCalendarsUsageDescription` in the plist

### ISSUE THREAD

**Issue by allenhumphreys** [insidegui/WWDC#423]
Just to be a good citizen, as it seems to be optional if the deployment target is < Mohave (or possibly the base SDK is < Mohave, the speaker possibly flubbed his terms)

**Comment by insidegui** [comment]
There are many things we need to do for Mojave 😅 We should maybe open a project for that 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by allenhumphreys** [comment]
Yes! I just didn’t want to forget it in the mean time 😄
