### ISSUE TITLE
Adopt the Dark Aqua appearance in Mojave

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#424]
With macOS Mojave, there's no need for us to use our custom dark appearance anymore since we can adopt the system's built-in Dark Aqua appearance. I think we should definitely do that and also adopt the user-defined accent color instead of forcing our own.

More information: 
https://developer.apple.com/videos/play/wwdc2018/210/
https://developer.apple.com/videos/play/wwdc2018/218/

**Comment by VicenteBorrell** [comment]
You sure about the accent color? 
It will dilute our “brand”! 😂

**Comment by insidegui** [comment]
I don't think it'd be an issue. That way our app would fit better in the system and automatically adopt the accessibility appearances.

**Comment by VicenteBorrell** [comment]
Can you have a setting for that? Like, a default or system color?
I still have to see how the many new colors look like… (shivers)

**Comment by spaz926** [comment]
Being a media-centric application do you truly think it is best for the light appearance to be an option?

Although I would assume iTunes keeps it's light appearance in Mojave, so maybe it _is_ best to adopt the adaptivity.

**Comment by insidegui** [comment]
Light appearance will not be an option.

**Comment by spaz926** [comment]
Ahh. Misread the OP. +1 for the idea.

**Comment by VicenteBorrell** [comment]
https://www.dropbox.com/s/85sbsvznybi7wif/screens.zip?dl=0

**Comment by VicenteBorrell** [comment]
https://www.dropbox.com/s/85sbsvznybi7wif/screens.zip

**Comment by allenhumphreys** [comment]
@insidegui Is this complete?

**Comment by insidegui** [comment]
Yeap
