### ISSUE TITLE
Add Forward and Backwards scrubbing keyboard shortcut

### ISSUE THREAD

**Issue by spaz926** [insidegui/WWDC#425]
Just a quick feature request. It'd be nice to be able to use the arrow keys to scrub the video forwards and backwards. So if I want to skip forward 15 seconds instead of pressing the UI button with my cursor I could just hit the right arrow key and vice versa for backwards with the right arrow key.

Thanks for the consideration.

**Comment by insidegui** [comment]
Duplicate of #97 ?

**Comment by spaz926** [comment]
Yes, but doesn't seem to be working in 6.0.3.

**Comment by insidegui** [comment]
Sorry, I meant #412

**Comment by spaz926** [comment]
Yep. Guess my search wasn't thorough enough. Close in favor of that one. ;)
