### ISSUE TITLE
When returning to current session video, PIP should pop back to the regular player

### ISSUE THREAD

**Issue by spaz926** [insidegui/WWDC#426]
I'm not sure if this is an oversight or intentional design, but when browsing sessions with a current video playing PIP mode is invoked. This is great.

But when returning to the current session being played PIP is still being used. Perhaps it should pop back into the regular player when you return to that session page.

**Comment by insidegui** [comment]
@VicenteBorrell @bcmn @allenhumphreys what do you think about this behavior?

**Comment by bcmn** [comment]
I think I'm the same as Allen -- before his comment I think my mood was the same: tracking "auto-pip" as you called it would definitely be the only case where it doesn't seem like it'd be infuriating to a different subset of users... but I think this project has previously tried to steer away from tracking _too many_ finicky states/user preferences. 🤔

**Comment by insidegui** [comment]
I agree with the above.

**Comment by insidegui** [comment]
Since most of the team has agreed that this was the right design decision, I'll close this issue for now.
