### ISSUE TITLE
App fails to launch on Sierra on my 2015 13-inch MBP

### ISSUE THREAD

**Issue by YacYac** [insidegui/WWDC#427]
I'm currently running the latest version of Sierra(10.12.6) a on a 13-inch macbook pro and I've downloaded the latest version of the app of WWDC.io. Any attempt to launch the app results in an immediate crash and appearance of the crashreporter.

[CrashLog.txt](https://github.com/insidegui/WWDC/files/2078215/CrashLog.txt)
.

**Comment by allenhumphreys** [comment]
Realm is reporting a "Permission denied" error when launching the app. Without being able to debug this live on your machine, I would suspect that something has happened to the permissions in your `~/Library` directory. If you execute `ls -lah ~/Library/Application\ Support/ | grep io.wwdc.app` you should see permissions like this:

```
drwxr-xr-x   11 <Your-User-Name>  832595117   352B May 30 15:40 io.wwdc.app
```

**Comment by YacYac** [comment]
Fixed. Thanks and sorry to trouble you with this!

**Comment by insidegui** [comment]
Don't worry, glad you managed to solve it :)
