### ISSUE TITLE
Icon Suggestion

### ISSUE THREAD

**Issue by VicenteBorrell** [insidegui/WWDC#43]
I wanted to suggest two icon options and, as @insidegui said, let the people vote ;)
What do you think?

(I didn't use the Apple logo for legal reasons, but I may release them separately in the future for personal use)

![wwdc apple ios icon](https://cloud.githubusercontent.com/assets/584834/7544562/75b331fa-f5ce-11e4-9b00-bc35018f0025.png)
![wwdc15 logo icon](https://cloud.githubusercontent.com/assets/584834/7543084/147c2754-f5c2-11e4-9086-8fe7935d721d.png)

**Comment by insidegui** [comment]
I think I like the second one.

**Comment by jakemarsh** [comment]
I vote the 2nd one as well! :+1:

**Comment by francocarbonaro** [comment]
My vote is for the second one too.

**Comment by VicenteBorrell** [comment]
OK then. I'll wait until the weekend and work on the second one!
I hope doing all the Mac icon sizes isn't a lot of work :S

**Comment by insidegui** [comment]
@VicenteBorrell When you're done, send me the icon with all the different sizes and the original source file so I can put It in the repository.
