### ISSUE TITLE
Add section titles on filtered list

### ISSUE THREAD

**Issue by pahnev** [insidegui/WWDC#430]
It would be nice to have the section titles showing also when the list is filtered in some way.

For example, from the schedule, it’s nice to see the videos in the order they are presented at WWDC, but I’m not really interested in the labs schedule. But if I filter the results, I really have to be looking at the description, to see which videos might be available right now.

Of course I could use the videos tab, but since those are ordered alphabetically it gets really hard to scan for new videos.
![section-title](https://user-images.githubusercontent.com/2078494/41084306-741d4f8e-6a3c-11e8-88d8-99bcd0aa566d.jpg)

**Comment by insidegui** [comment]
This is a bigger issue that will require major changes to our list, I'll close this for now and we'll re-evaluate when the priorities change.

**Comment by JoshHrach** [comment]
I was just about to open an issue on this. Has there been any change to the priorities on this?

**Comment by insidegui** [comment]
Nope. Would require a massive re-engineering of the way our listing works. I believe both @allenhumphreys and @davedelong have done some experiments and came to the same conclusion.

**Comment by JoshHrach** [comment]
Understood. Thanks for explaining. 👍🏻

**Comment by allenhumphreys** [comment]
@JoshHrach I have an implementation that won't be considered for merge/release until after WWDC, if you'd like to take advantage of it, you're welcome to checkout https://github.com/insidegui/WWDC/pull/548 and build it locally. iCloud syncing doesn't work when you build locally, otherwise the experience should be identical!
