### ISSUE TITLE
[Feature Request] Add copy session url to clipboard functionality 

### ISSUE THREAD

**Issue by myurieff** [insidegui/WWDC#431]
I think it would be awesome to have an option to copy the currently watched session URL to clipboard, for easy sharing with colleagues. 🙃

There's an action sheet, but some services don't support it. For example, Slack.

Thanks! ✌️

**Comment by allenhumphreys** [comment]
This is pretty simple to implement. We might need an icon though.

**Comment by insidegui** [comment]
Implemented by @allenhumphreys with an icon I provided, will be in 6.1
