### ISSUE TITLE
Audio and Video Stop Working after PIP with 1.5x speed

### ISSUE THREAD

**Issue by PaulSolt** [insidegui/WWDC#434]
I was trying to full-screen to get my notes + the video in split screen ... and then hit PIP and then things got wonky, and the audio/video stopped playback. 

I don't believe the video was downloaded, and I think I was streaming it at 1.5x. The image player bar looks funky, like it's not downloaded/cached, and then part of it is. See below.

Actual: I saw the time increasing, but no video/audio.

I expected the video to play normally

- Version of macOS
10.13.5

- Version of the app

6.0.3
- What were you trying to do when the issue happened

I was trying to get a fullscreen video, tried to use PIP, couldn't get it to stretch out, and then things stopped working.

[Playback Issue Video](https://youtu.be/fR73xe8l1XM)

- Any particular hardware/software configuration you have that might be affecting the app

MacBook Pro 2016 + Thunderbolt 27"

- If it is a crash, please provide the crash log
- If it is a hang (beach ball), please provide a process sample
- If it is a wrong behavior, list all steps required to reproduce it
- Please add screenshots if you think they might help us diagnose the issue

![playback stopped watching 1 5x speed](https://user-images.githubusercontent.com/371902/41124361-bca56f06-6a6f-11e8-8dde-9656ab8bdfe6.png)

**Comment by PaulSolt** [comment]
After I pressed the rewind 15 seconds, it worked, but then after watching again, audio stops around 20:00 minutes in "What's New in Cocoa Touch" 2018: Session 202.

**Comment by insidegui** [comment]
We highly recommend downloading sessions if you prefer to watch at higher speeds. `AVFoundation` seems to have issues with streaming at >1x.

**Comment by insidegui** [comment]
See #443

**Comment by weiran** [comment]
A rather heavy handed approach to fixing this is to use [VLCKit](https://code.videolan.org/videolan/VLCKit) for video playback, which I've had to do to get around `AVFoundation` limitations or bugs, especially when streaming over HTTP.

Whether it's worth the effort and change just to fix this bug is debatable.
