### ISSUE TITLE
Allow users to filter down to live sessions

### ISSUE THREAD

**Issue by bcmn** [insidegui/WWDC#435]
I'm not 100% sure this is the correct solution, but over the last few days I've found myself scrolling up & down the table view just to see if there are any live sessions currently available to watch. This seems symptomatic of a missing UX feature of some sort. This could be in the form of a "live" filter on the Schedule tab only, though this would have no benefit for the rest of the year, which gives me pause 😕

**Comment by bcmn** [comment]
I think I've previously pondered the idea of a contextually-sensitive "live tab" which only appears when content is live & simply links directly to each session. I know we want to limit the number of tabs long term, so perhaps that wouldn't be suitable. The behaviour described would also introduce complexity. 🤔

**Comment by insidegui** [comment]
When we have the Featured tab working, we'll definitely show the live sessions there at the top, so that's part of the solution, but I think filtering would be cool as well.

**Comment by bcmn** [comment]
Aha, I didn't realise/had forgotten (?) that. Sounds good.
