### ISSUE TITLE
Add a warning when streaming at >1x

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#443]
We've had many issues reported before about playback glitches when streaming at speeds higher than 1x. We've tried many workarounds and it seems to be an issue with `AVFoundation` which we can't do anything about (other than filing radars).

I proposed that we add a warning the first time a user tries to stream a video at higher speeds suggesting that they download the video instead of streaming, otherwise we'll keep getting repeated issues opened for this.

**Comment by PaulSolt** [comment]
Thank you! A warning is a great idea.

**Comment by insidegui** [comment]
TODO: Check if addressing #465 has an effect on this issue.

**Comment by the7thgoldrunner** [comment]
Is this fixed? I'm asking because #465 has been closed and these two issues are marked as related.

**Comment by allenhumphreys** [comment]
I think we’re holding off to get feedback on whether the related issues addressed the underlying problem here.

**Comment by the7thgoldrunner** [comment]
Got it. Thanks!

**Comment by insidegui** [comment]
I haven't been able to reproduce issues with streaming at over 1x for a while. Closing this issue for now.
