### ISSUE TITLE
The App Asks for Microphone Access on Mojave

### ISSUE THREAD

**Issue by ekhodykin** [insidegui/WWDC#445]
On macOS Mojave the app asks for microphone permission. To reproduce just open the app and try to play any video. I captured the whole process on video, just in case: https://photos.app.goo.gl/pFPZReU1hLZQCbgp2

I'm using the first beta of Mojave and WWDC app is 6.0.3.

**Comment by insidegui** [comment]
This is probably a bug in this first beta, since the app uses `AVPlayer` for video playback. I'll file a radar about this.

**Comment by insidegui** [comment]
rdar://40947251 ([OpenRadar](http://www.openradar.me/radar?id=5039063920803840))

**Comment by insidegui** [comment]
My radar was marked as a duplicate, so they're already on it 😄

**Comment by sgtcoolguy** [comment]
@insidegui Hey - any idea if there was movement on this? I'm running into similar issues on an entirely separate repo/app, but this is about the only place I can find reference to this bug.

**Comment by insidegui** [comment]
I believe this is not happening anymore since we linked the app to the 10.14 SDK. @allenhumphreys have you experienced this issue on Mojave? It's fine for me here...

**Comment by sgtcoolguy** [comment]
I'm running into a similar issue in that we're running some automated tests on an iOS app running in an iOS 12.0 Simulator on macOS Mojave (and Xcode 10). Trying to use the AVPlayer APIs to play a movie file in the iOS app prompts the permissions for microphone in Mojave. This is in our CI node setup, so I don't really ant to try and upgrade our build nodes to Xcode 10.1 and macOS 10.14.1 unless I have good reason, like a fix for this 😄

**Comment by allenhumphreys** [comment]
This hasn't happened with our app. I have had Xcode and Android studio both ask for microphone permissions completely randomly, though. So something isn't quite right out there.

**Comment by insidegui** [comment]
I'm closing this since it's not applicable anymore.

**Comment by ekhodykin** [comment]
It happens for me as well with our CI setup for UI tests. 

@sgtcoolguy It would probably be a good idea to post an additional bug report to http://bugreport.apple.com/. Maybe it will help to adjust this bug's priority. 

But the WWDC app itself is OK, I can't reproduce this issue anymore even when I create a new user and run a fresh download of the app from it.

**Comment by insidegui** [comment]
> But the WWDC app itself is OK, I can't reproduce this issue anymore even when I create a new user and run a fresh download of the app from it.

That's good to know, thank you!

**Comment by andywarwick** [comment]
There seems to be two issues here: microphone access for both Xcode and the app itself.

Your app (or a test) can prompt/fail for either or both, though not always on same run.

Both of these dialogs must be approved to allow access, after which the permission persists between Xcode and Simulator resets or restarts.

You can confirm access has been approved for Xcode in System Preferences -> Security & Privacy-> Microphone, where you should see the Xcode in the UI.

The app itself, approved or not, won't appear in the UI here, however.

If you are unsure it the app has been approved, reset all the microphone permissions with 'tccutil reset Microphone' in the Terminal, and re-run your app/test, until both dialogs have been shown and approved.
