### ISSUE TITLE
Copy session's link

### ISSUE THREAD

**Issue by jdisho** [insidegui/WWDC#447]
Hi 👋

Is it possible to copy the link of a session from the app?  

- Are you running the latest version of the app?  **YES**
- Are you running a release, stable version of macOS? **YES**
- Have you looked at previous issues to see if you're having an issue that's already being worked on? **YES**
- Have you read the Code of Conduct, and will you uphold it's values? **YES**
- Version of macOS **10.13.5**
- Version of the app **6.0.3**

**Comment by insidegui** [comment]
Already implemented in #419

**Comment by insidegui** [comment]
Coming in 6.1
