### ISSUE TITLE
Sound cut off at 2x playback speed

### ISSUE THREAD

**Issue by lmjabreu** [insidegui/WWDC#448]
- Version of macOS: 10.13.5 (17F77)
- Version of the app: 6.0.3
- What were you trying to do when the issue happened: Play State of the Union at 2x speed
- Any particular hardware/software configuration you have that might be affecting the app: no, 200Mb internet, latest MacBook Pro 15", Netgear Orbi mesh wifi (connected to main node, 1m away), nothing installed that is designed or would interfere with audio/kernel/macOS core services.
- If it is a wrong behavior, list all steps required to reproduce it: Set playback speed to 2x on any video, play through until sound cuts off.

PS: some speakers talk really slowly, eg Platforms State of the Union, 2x isn't fast enough, wouldn't mind having 3x or 2.5x. I know, feature request, feel free to ignore.

**Comment by insidegui** [comment]
See #443
