### ISSUE TITLE
Some UX suggestions

### ISSUE THREAD

**Issue by RayPS** [insidegui/WWDC#449]
I have some UX suggestions:

- [x] Add an hot key to jump backward/forward
- [ ] Add a spinner when jumping to an unbuffered position
- [x] Use space bar to pause or play
- [ ] Remove from list when a video marked as watched with "unwatched" filter is enabled.

**Comment by insidegui** [comment]
1 has been addressed. 2 is a good point. 3 should already work, if it’s not working, open another issue because it’s a bug. 4 can be done by filtering, I have no interest in implementing a permanent filter for watched videos. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by allenhumphreys** [comment]
@insidegui i think 4 is referring to a live updating filter. Today you have to clear and set the filter again when the criteria have been met after the filter is applied.

**Comment by insidegui** [comment]
Got it

**Comment by bcmn** [comment]
I changed the original list to be a checklist just to make things a bit clearer. Forward/backward key command is now in master & will be included in the next release.

**Comment by lumaxis** [comment]
@insidegui Opened #463 for 3 since this appears to indeed be a bug.

**Comment by insidegui** [comment]
Number 2 will be addressed in #465, number 4 is a large issue and deserves its own issue, which I'll be opening.
