### ISSUE TITLE
Feature Request: 1.1x speed

### ISSUE THREAD

**Issue by mergesort** [insidegui/WWDC#454]
I'd like something a bit faster than the normal speed, but not quite as fast as 1.25x.

Thanks a lot!

**Comment by insidegui** [comment]
At this point I think we should allow the user to determine their preferred speeds since this is not the first time someone has asked for another speed option 😅

**Comment by mergesort** [comment]
Sounds even better to me. 😄

**Comment by insidegui** [comment]
@allenhumphreys Maybe use `NSUbiquitousKeyValueStore`? If you'd like to make this more generic, maybe provide a way for the app to inject something that conforms to a protocol so the player doesn't have to know about iCloud vs. user defaults...
