### ISSUE TITLE
Show time preview when hovering over the timeline

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#456]
I think we should show a preview for the time under the mouse cursor when hovering over the timeline, it would make it a lot easier to jump into a specific point in a video.

**Comment by insidegui** [comment]
Just to clarify: I mean we should show what time the current cursor position represents, similar to how we show the time when hovering over a bookmark.

**Comment by bcmn** [comment]
I had literally started making a screen-capture to annotate into a mockup for this yesterday 😝

**Comment by bcmn** [comment]
Just to document what I think we're both referring to: 

**Current Behaviour**
![current_behaviour](https://user-images.githubusercontent.com/11646957/41276683-e8de16d0-6e1c-11e8-8769-c251ac20a798.png)

**Preferred Behaviour**
![preferred_behaviour](https://user-images.githubusercontent.com/11646957/41276702-f62a9d9a-6e1c-11e8-9821-94ee9ef901f4.png)

There's an obvious readability risk here, but I feel this feature shouldn't *inherently* require a background to the text, especially if we address the gradient issue described in #399.

**Comment by insidegui** [comment]
We could use white text with a dark border/shadow to prevent readability issues.

**Comment by insidegui** [comment]
That's great! Go ahead

**Comment by dinesharjani** [comment]
@insidegui can you give me ticket assignment rights, so I can assign myself to issues / tickets?

**Comment by insidegui** [comment]
@dinesharjani That's not necessary, stating in a comment that you're doing it is enough 😉

**Comment by dinesharjani** [comment]
![image](https://user-images.githubusercontent.com/1042411/43646006-857ebe72-972b-11e8-9f3d-ca3821f8603c.png)

I'm close to having a pull request.

**Comment by insidegui** [comment]
Nice! May I suggest that the bottom of the time tooltip be aligned with the current time and time left?

**Comment by dinesharjani** [comment]
I can do that. What I don't know what to do about is what happens when the preview overlaps the time labels; I thought of making them invisible when previewing the time, but I have no direct delegate from the Timeline View object to the Player View object. Should I add one or leave it for you guys to decide?

**Comment by insidegui** [comment]
It could rise when it's close to the edges or maybe we could not show it when too close to the edges. I feel like it's more useful in the middle of the video.

**Comment by insidegui** [comment]
@bcmn @VicenteBorrell @allenhumphreys Any opinions on the above?

**Comment by allenhumphreys** [comment]
My first thought is to just limit it's movements so it can only come within 10 pts of the time labels.

**Comment by insidegui** [comment]
> limit it's movements so it can only come within 10 pts of the time labels

The simple solution is often the best one :)

**Comment by dinesharjani** [comment]
I'm so happy we finally merged #499 in! 

That being said, I think we can close this issue now 🥇

**Comment by allenhumphreys** [comment]
Thanks @dinesharjani! I wanted to let you know, in case you didn’t, that you can [“link” a PR to an issue](https://help.github.com/articles/closing-issues-using-keywords/). Though I’m not sure if it works if the PR author doesn’t have push access to the target repo. Maybe give it a try on your next work!

**Comment by insidegui** [comment]
Thanks @dinesharjani !
