### ISSUE TITLE
Speed isn't maintained after switching videos.

### ISSUE THREAD

**Issue by yarnichat** [insidegui/WWDC#458]
1. Play a video and change the speed to, say, 2x.
2. Play a different video.
3. The speed button still says 2x, but the video plays at 1x (!).

The speed setting should be preserved when switching between videos.

**Comment by the7thgoldrunner** [comment]
If we still want to fix this, I think I'll take it.

**Comment by allenhumphreys** [comment]
@bcmn Any issue with that?

**Comment by bcmn** [comment]
Yeah that’s fair enough, I’ve had a lot of things come up recently & not
had time to fully update this stuff to unassign myself and everything. My
bad.
