### ISSUE TITLE
Time Remaining Label should be monospaced

### ISSUE THREAD

**Issue by AnalyzePlatypus** [insidegui/WWDC#460]
# System & Version
- macOS 10.13.4
- WWDC 6.0.3

# Current Behavior
Here's current behavior of the time remaining label:
![current behavior mov](https://user-images.githubusercontent.com/18376110/41319944-4f174cf8-6ea6-11e8-8975-717de01fce9c.gif)
The label width is constantly changing.

Exact location:
<img width="360" alt="indicate relevant label" src="https://user-images.githubusercontent.com/18376110/41319825-cb39d324-6ea5-11e8-8c72-7fec17f94210.png">

## What should it do?

**Use the system monospace font for this label.**

Here's a comparison from [WWDC 2015 Session 804](https://developer.apple.com/videos/play/wwdc2015/804/), "Introducing the New System Fonts":
(The top text in monospaced; bottom text is proportional)

![compared mov](https://user-images.githubusercontent.com/18376110/41319629-2d254b5a-6ea5-11e8-9591-4079dd05dea3.gif)

We should be using the monospace variant for the counters in the playback controls.

There's an easy API for this:
```swift
NSFont.monospacedDigitsSystemFontOfSize(mySize weight:)
```

## More Info

* [WWDC 2015 Session 804](https://developer.apple.com/videos/play/wwdc2015/804/), especially **between 26:16-28:47**. I highly recommend this segment. It's only ~2 minutes!
* Docs for [NSFont.monospacedDigitsSystemFontOfSize](https://developer.apple.com/documentation/uikit/uifont/1619022-monospaceddigitsystemfontofsize)

**Comment by bcmn** [comment]
Good catch, thanks very much. Very comprehensive issue, too! 👏🏻
