### ISSUE TITLE
Cannot open app

### ISSUE THREAD

**Issue by Milos** [insidegui/WWDC#466]
I can't open the app even though I'm running the latest version of the app and MacOS (10.13.5).  I've tried reinstalling app but without success. 

![ezgif-2-5ac66adefd](https://user-images.githubusercontent.com/1482759/41482151-f0097160-70d4-11e8-9eaa-a06d648356c9.gif)

**Comment by insidegui** [comment]
Is there a crash log you could send us? I can't really know what's happening based on that gif.

**Comment by Milos** [comment]
Sure thing Guilherme.

**Crash log:** [WWDC_2018-06-15-193547_milos-mb.txt](https://github.com/insidegui/WWDC/files/2108305/WWDC_2018-06-15-193547_milos-mb.txt)

**Update**: After looking at the crash log, I saw what was causing the crash. It was unable to initialize Realm because of Incompatible histories. I deleted WWDC app and removed *io.wwdc.app* from the *Application Support* and installed WWDC app again. It solved the issue for me. 

I guess we should manually remove *io.wwdc.app* from the *Application Support* when uninstalling WWDC app.

**Comment by insidegui** [comment]
This was caused by some inconsistency in the database file, unfortunately it's been deleted now so we can't investigate any further 😅

I'm glad you managed to solve it.
