### ISSUE TITLE
User Defined Playlists

### ISSUE THREAD

**Issue by vichudson1** [insidegui/WWDC#482]
I saw a few issues discussing Curated Playlists, but didn't see anyone mention user created ones. As a user it would be nice to be able to create my own playlists to watch and possibly even share with others as well as view others shared with me. Maybe use a simple plist or some other easily shareable format.

**Comment by insidegui** [comment]
I'm not sure I want this feature. Opinions? @bcmn @allenhumphreys

**Comment by vichudson1** [comment]
So maybe the user sharing would be overkill, but playlists would be a value add for me. I could create lists of related session then just queue them up and let it play.

**Comment by insidegui** [comment]
I don't think it would get much use to justify its complexity. I certainly wouldn't use that.

**Comment by insidegui** [comment]
Let’s wait for Ben and Allen to give their opinions 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bcmn** [comment]
Queueing up multiple sequential sessions seems reasonably suited for the “Now Playing” functionality discussed in #289.

As for the rest, I definitely don’t think Gui & I overlooked this possibility when we were discussing curated playlists. To me, the sharing would be the heart of user-created playlists; who is rewatching their own collections of long-form technical talks? It seems like one the wider community could benefit from a less ephemeral method of sharing favourites  — at the moment sharing of sessions seems to be heavily constrained to “hope you time it right to see some relevant tweetstorms”. 

But there’s a risk of it requiring significant UI work — the app is currently hugely focused towards consumption over creation, & we also have little knowledge (as far as I know?) of how many people already utilise & benefit from perhaps the only existing “creation” feature in the app, bookmarks. 🤔

**Comment by insidegui** [comment]
> we have little knowledge (as far as I know?) of how many people already utilise & benefit from perhaps the only existing “creation” feature in the app, bookmarks

Judging by the fact that bookmarks have some annoying bugs (which I was too lazy to report myself) and nobody has reported any I suspect the usage is very small.

We always need to judge how much it is worth committing our time to a new feature, there are currently only around 4 people actively working on the project on their free time, we need to be very picky about features.

**Comment by bcmn** [comment]
Given the responses, I think we should close this issue for now. We can always reopen it if we have a change of heart.
