### ISSUE TITLE
Use time stretching for fast playback rates without audio distortion

### ISSUE THREAD

**Issue by shadowfacts** [insidegui/WWDC#486]
The WWDC app would benefit from using [time stretching](https://en.wikipedia.org/wiki/Audio_time_stretching_and_pitch_scaling) when the playback rate is greater than 1 in order to speed up the content without audio distortion or affecting the pitch of the audio significantly.

To compare the differences with/without time stretching, open a video in Chrome and Safari and change the playback rate (the YouTube player has this option, or by modifying the `playbackRate` JS property of a `<video>` element from the console) and see how in Chrome the audio still sounds pretty natural, but sounds much more distorted in Safari.

I find audio using time stretching instead of the normal playback rate increase to be much more pleasant to listen to, and I would love for this to be supported in the app.

I believe this is possible using [AVAudioUnitTimePitch](https://developer.apple.com/documentation/avfoundation/avaudiounittimepitch), but I'm not sure how to use AVFoundation audio units with AVPlayer or integrate it into the app.

**Comment by insidegui** [comment]
We had someone implement something like this, but we disabled it because of other issues. We're currently working on changes to the player that are going to change the way it behaves when playing at faster speeds.

@allenhumphreys Is something you'd like to take a look at?

**Comment by allenhumphreys** [comment]
@shadowfacts 
`AVAudioUnitTimePitch` appears to be for the audio engineering portion of AVFoundation and there is no apparent API on AVPlayer/Asset/PlayerItem that could make use of it. We are using the [time domain](https://en.wikipedia.org/wiki/Audio_time_stretching_and_pitch_scaling#Time_domain)-based stretching built into AVFoundation and supported by AVPlayerItem's `audioTimePitchAlgorithm` property. It is configured on [this line](https://github.com/insidegui/WWDC/blob/master/PlayerUI/Views/PUIPlayerView.swift#L297)

The article cited doesn't clearly explain the why behind the difference in your experiences in Safari and Chrome. It is likely that you're just hearing different implementations of the algorithms mentioned in the article. One thing that is certain is that we are not using the resampling method, as that would result in a very different experience (chipmunks at high speed). You can experience that for yourself by setting the `audioTimePitchAlgorithm` to `.varispeed`. (to great comic effect!)

**Comment by insidegui** [comment]
I'm closing this since it's not an actionable issue.
