### ISSUE TITLE
Save split size between launches

### ISSUE THREAD

**Issue by dmthomas** [insidegui/WWDC#49]
Thanks for adding the window size saving so quickly! If I adjust the split and close the app, when I relaunch the split is 50% | 50%, dead center. It would be nice if the split setting was saved as well.

**Comment by insidegui** [comment]
I'm working on that right now :)

**Comment by dmthomas** [comment]
Awesome!

**Comment by dmthomas** [comment]
It seems like it's mostly respecting the split values you're saving in the plist, but when you relaunch the app, there's some auto sizing that overrides the exact values and resets them to that size. Maybe it's AutoLayout doing it based on the content size of the right pane.

**Comment by insidegui** [comment]
It's working just fine here.
Try deleting the preferences, close the app and delete `~/Library/Preferences/br.com.guilhermerambo.WWDC.plist` and autosave files `~/Library/Saved Application State/br.com.guilhermerambo.WWDC.savedState`

After that run `killall cfprefsd`

**Comment by dmthomas** [comment]
Okay debugging it this is what I found.

In SplitManager.swift, the didSet on the splitView var, never seems to get called to set the delegate, which in turn never fires "func splitViewDidResizeSubviews(notification: NSNotification)" to save the sidebarWidth.

Hacking on it a bit, in VideosViewController.swift where you create the SplitManager, I tried setting the delegate there.

if let splitViewController = parentViewController as? NSSplitViewController {
            splitManager = SplitManager(splitView: splitViewController.splitView)
            splitManager.splitView.delegate = splitManager
        }

It causes the delegate function to get called and save the sidebarWidth, but it sets it into an infinite loop of thinking it's resized and saving over and over. I finally saw the sidebarWidth key in the preferences file after this though.

But, when I relaunch the app, it overwrites the preference because splitViewDidResizeSubviews gets called when the storyboard loads and it sets the value from there.

Hope this is helpful.

**Comment by insidegui** [comment]
The big question here is why It works on my machine and doesn't work on yours. I will see what I can do.

**Comment by dmthomas** [comment]
I was going to say maybe it was Xcode 6.4 beta 3, but I just tried 6.3.1 even.

Maybe you can send me the archived binary you built and then we'll know if it's just user error for me building with Xcode or something.

**Comment by insidegui** [comment]
I don't think It's a build issue, but just to be sure, here's my build: http://cl.ly/1t2v450z3x3I/download/WWDC_split_test.zip

Also, what version of OS X are you on? I'm running `10.10.3 (14D131)`

**Comment by dmthomas** [comment]
That's really interesting. That binary doesn't set the sidebarWidth in the preferences either.

I'm running <code>10.10.3 (14D136)</code>

**Comment by insidegui** [comment]
Can you create a new user and run this binary there? That way we can check if it's something broken on your account. I will add the "help wanted" tag to this issue, we need more people to test this to see if It's only working on my machine or if It's only NOT working on yours.

**Comment by dmthomas** [comment]
I tested the binary on a Mac Mini running <code>10.10.3 (14D136)</code> and saw the same results. No sidebarWidth saved in the preferences and the window split wasn't being restored.

A Mac Pro running <code>10.10.1</code> and saw the same results.

A Macbook Pro running <code>10.10.3 (14D136)</code>. Here I saw different results. It actually was saving the application state, so when I relaunched the window split was saved, but the sidebarWidth wasn't saved in the preferences here either. So it seemed to only work from the application state.

I'm not sure why application state isn't being saved on the other 3 machines. I guess if application state was a sure thing, you wouldn't even need to save the sidebarWidth and restore it.

**Comment by dmthomas** [comment]
On your machine is it restoring off application state, or do you actually see the key being set in the preferences file for sidebarWidth?

**Comment by insidegui** [comment]
@dmthomas Please test this new binary to see if It's fixed before I commit: http://cl.ly/0F1K3C3l1s0O/WWDC_splitrestore_fixed.zip

**Comment by dmthomas** [comment]
Sweet! That seems to work now. I see the DividerPosition setting you're saving into the prefs now.

It works fine, I just noticed that you see the "original" window for a split second before it loads the DividerPosition that's saved. Maybe WillAppear vs DidAppear/DidLoad?

**Comment by insidegui** [comment]
Open a new issue for the split second thing, this one is done.

**Comment by dmthomas** [comment]
Cool, thanks for working on this. It's makes the app so much more usable for me and I hope other people benefit and appreciate it!
