### ISSUE TITLE
Subtitles are not in sync with video if playback speed is not 1x

### ISSUE THREAD

**Issue by rshev** [insidegui/WWDC#498]
- Version of macOS: 10.13.6 (17G65)
- Version of the app: 6.0.4
- What were you trying to do when the issue happened: watch videos with subtitles on on playback speed 1.25x
- Any particular hardware/software configuration you have that might be affecting the app: nope
- If it is a wrong behavior, list all steps required to reproduce it:
1. start a video (for example "Embracing Algorithms" 2018-223)
2. enable subtitles (English)
3. put the playback speed to 1.25x

**Comment by insidegui** [comment]
I was unable to reproduce the issue, but it sounds similar to an issue we've been having with audio when streaming at >1x. Does that happen every time? Can you do a screencast showing the steps leading up to the issue? Thanks

**Comment by JetForMe** [comment]
I also see audio get way out of sync with the video if I pause or rewind at 1.5x

**Comment by insidegui** [comment]
We have basically settled on not supporting streaming at >1x but unfortunately never reflected this in the app itself. Again, if someone knows some `AVFoundation` magic that can fix this, let us know.

**Comment by insidegui** [comment]
I'm locking this thread since we don't plan on addressing this. Again, if someone has a solution please feel free to open a pull request.
