### ISSUE TITLE
Download Videos

### ISSUE THREAD

**Issue by b3ll** [insidegui/WWDC#5]
It'd be awesome to be able to download (or batch download videos!) :D

**Comment by insidegui** [comment]
Batch download is outside the scope of the app, but download like on the iOS app I plan on adding :)

**Comment by b3ll** [comment]
sweet! 🎉

**Comment by bishalg** [comment]
Where are the downloaded video saved in local drive ?
Also, there should be option to download SD or HD video.

**Comment by insidegui** [comment]
@bishalg Open the preferences, you can set the downloads folder there.

I think there is not enough demand for download of SD videos to justify the amount of work and maintenance cost It would take to implement It.

**Comment by arbab** [comment]
I still think if there can be a flexibility to choose between SD and HD videos at the time of downloading, it would be a great option. (Consider I have to download and watch it while inside MTA train, I wouldn't want to download and transfer a heavy file to my phone.)
