### ISSUE TITLE
DividerPosition gets restored while window is visible

### ISSUE THREAD

**Issue by dmthomas** [insidegui/WWDC#50]
When the app first loads, the "original" window appears for a split second before it loads the DividerPosition that's saved. Maybe WillAppear vs DidAppear/DidLoad?

**Comment by insidegui** [comment]
I think `awakeFromNib` is the answer. Please test this: http://cl.ly/320m1A2O121W/WWDC_splitsecond_split.zip

**Comment by dmthomas** [comment]
This build seems to work fine with the changes to <code>awakeFromNib</code>, but it seems like you regressed on the DividerPosition restoring in it.

**Comment by insidegui** [comment]
You mean the position is not being restored?

**Comment by dmthomas** [comment]
Yes. It is not being restored in this build.

**Comment by insidegui** [comment]
😅

**Comment by insidegui** [comment]
Is It better now? http://cl.ly/2T05221Y2j0H/WWDC_split2.zip

**Comment by dmthomas** [comment]
It is properly restoring the divider position again, but it still flashes the initial nib layout before it adjusts. I'm not sure if there's a way to fix that or not.

Maybe I'm just being picky. :-)

**Comment by insidegui** [comment]
It's freakin' autolayout doing Its thing :(

I'll leave this opened so others can try to fix It.

**Comment by dmthomas** [comment]
Haha. Cool.

Maybe I'll mess with it myself and see.

**Comment by flexaddicted** [comment]
The divider restore to the default width when the application is visible. To observe the behaviour, open the app. Drag the divider in order to reach a specific width. After a while the divider returns to the default width.
