### ISSUE TITLE
"Save a copy..." for Downloaded Sessions

### ISSUE THREAD

**Issue by allenhumphreys** [insidegui/WWDC#511]
Just a thought I had while working on the downloads window. Sometimes I'd like to trim down a clip to send to someone and finding it/getting a copy of it to work with would be handy. Could go in the share menu possibly.

I don't think we want to encourage a "Reveal in Finder" type mechanism as users doing anything to the files other than deleting them could be disastrous.

**Comment by insidegui** [comment]
Sounds like a good idea and not too hard to implement. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bcmn** [comment]
I've really liked the idea of being able to bookmark a chunk of video, instead of a point, for quite a while now. I wonder if this idea would work well with it -- the ability to either link to the chunk, or export the chunk as a new file to share. 🤔

**Comment by allenhumphreys** [comment]
My workflow is to get the file, trim with QuickTime and then share.

**Comment by insidegui** [comment]
> My workflow is to get the file, trim with QuickTime and then share.

That's not too hard to implement with `AVFoundation`

**Comment by allenhumphreys** [comment]
No, but the UI though... big can of worms turning the app into an editor.

**Comment by insidegui** [comment]
I believe `AVKit` has a built-in control that can handle trimming.

**Comment by insidegui** [comment]
Just had a thought about how cool this feature could be for sharing short clips from the videos, but then I thought about copyright laws and got depressed 😑
