### ISSUE TITLE
[Missing UI Element] - iCloud Sync Toggle 

### ISSUE THREAD

**Issue by spaceleviathan** [insidegui/WWDC#521]
- Release version of macOS 10.14.1 (18B75)
- Latest version (from WWDC.io) of WWDC.app - 6.1

In the latest version the toggle or checkbox for iCloud sync (beta) has disappeared. 
The label is there in the settings panel, but not the toggle to activate it. 
_(perhaps this is intentional?)_
I haven't seen this identified anywhere, my apologies if this is a duplicate. 

Would love to have syncing back to transfer everything between work & home Macs.

Thank you for all the good work.

<img width="704" alt="wwdc-version" src="https://user-images.githubusercontent.com/13920261/48438704-8afd7100-e752-11e8-94dd-44cf3a8b8091.png">

<img width="686" alt="wwdc-preferences" src="https://user-images.githubusercontent.com/13920261/48438705-8afd7100-e752-11e8-807e-2a00f340580b.png">

**Comment by allenhumphreys** [comment]
Confirmed

**Comment by insidegui** [comment]
Oops 🥴
