### ISSUE TITLE
Version 6.1 shows only session from 2018

### ISSUE THREAD

**Issue by pzoltowski** [insidegui/WWDC#523]
I just updated WWDC to 6.1 and noticed I cannot see anymore sessions from different years. It shows only from 2018 even though I have also many sessions from 2017 and previous years downloaded. I have only 'All events', 'All platforms', 'All Tracks' combo boxes for filtering. 'All events' have only 'Sessions' and 'Labs and others' options.
My setup:
10.13.6 High Sierra
Macbook Pro 15'' 2012 unibody 
I'm running Raid 0 setup with JHSF+

**Comment by insidegui** [comment]
Switch to the "Videos" tab.
