### ISSUE TITLE
Light UI Option (or basing it off the user's macOS theme choice)

### ISSUE THREAD

**Issue by ScherisMarie** [insidegui/WWDC#524]
I'm running the latest version of the application, along with the latest version of macOS 10.14.

Would it be possible down the road to add a light UI option as an option (or since Dark Mode support is built into the OS, change the UI theme based on the user's choice).

I noticed in the closed issues that it was mention "Light UI will not be an option", but I can't use dark UIs without straining and blurring my eyesight due to bad astigmatism. For me, light text on a dark background (i.e. "dark mode") causes the letters to blur together and strains my eyes. (I believe the scientific explanation is something along the lines of due to the difference in light the eye is taking in and how astigmatism affects that.)

macOS's dark mode makes this not as bad due to the color theming they do against the desktop background, but it's still not usable for me unfortunately.

I know this application is media focused (and thus I understand why right now the default theme is a dark one), but accessibility-wise this would be a big benefit for me as an optional option.

**Comment by insidegui** [comment]
I understand your frustration, but we've decided to not implement this. Sorry.

**Comment by literalpie** [comment]
This is very disappointing. I am colorblind and cannot read the text of selected items in the list. White text on a light blue background is nowhere close to accessibility standards!

<img width="442" alt="image" src="https://user-images.githubusercontent.com/20398475/59140340-33328b80-896a-11e9-9084-9e16a366a584.png">

**Comment by insidegui** [comment]
That's a bug we're tracking on #546 . Keep in mind this is an open-source project we do on our free time. We're not your employees 😉 This type of attitude against open-source maintainers is what makes many of us give up on doing open-source work altogether.
