### ISSUE TITLE
Improvement Suggestion: Option to Limit the Number of Concurrent Downloads

### ISSUE THREAD

**Issue by mediter** [insidegui/WWDC#525]
Currently (version 6.1 with macOS 10.14.3 (18D109) ), it is very nice that we can see and control every download in Download Manager. However, all the downloads start at the same time. If you happen to download a whole bunch of them, each one of them would progress slowly, especially during the day when network usage is high. And very likely some of them would fail when that happens.

Having the option to limit the number of concurrent downloads could help reduce failed downloads, while the rest are set to "wait to download" status.

**Comment by bcmn** [comment]
Good idea, thanks for the suggestion -- it definitely sounds like we should have a max in there.

UX-wise, I suspect an option would be quite a tricky preference for a user to be presented with. I'm not sure a user would have all the information as to the trade-offs. Perhaps a limit is all that is needed.

**Comment by insidegui** [comment]
Weird, I thought the `URLSession` mechanism would manage that for us, I believe it does on iOS. I agree we should come up with a limit and apply it, I'm against adding a preference for it.

**Comment by allenhumphreys** [comment]
It *kind of* does. In my development, it mostly limited active downloads to 3 while the remaining ones sit in a pending state. And this behavior was somewhat dynamic, so if you are on a slow it will start fewer. I agree that a setting would be a nice to have. I'm not sure what the standard use case it. For example, is it typical to download between 1-5 at a time, or an entire year.
