### ISSUE TITLE
Cannot open interface builder

### ISSUE THREAD

**Issue by brutella** [insidegui/WWDC#53]
Building the project always results in errors because the xib files cannot be opened.

`WWDCTranscriptViewController.xib: The document "WWDCTranscriptViewController.xib" could not be opened. The operation couldn’t be completed. (com.apple.InterfaceBuilder error -1.)`

The console says

    19/05/15 14:51:28,235 ibtoold[54494]: -[NSButton setSpringLoaded:]: unrecognized selector sent to instance 0x7fa54d5b9040
    19/05/15 14:51:28,235 ibtoold[54494]: Exception raised while unarchiving document objects - -[NSButton setSpringLoaded:]: unrecognized selector sent to instance 0x7fa54d5b9040

My configuration:
- Xcode 6.3.1/6.3.2
- Yosemite 10.10.3

**Comment by insidegui** [comment]
I don't know, file a radar I guess...

**Comment by brutella** [comment]
Which configuration are you using?

**Comment by insidegui** [comment]
Xcode 6.3.1 (6D1002), Yosemite 10.10.3 (14D131)
