### ISSUE TITLE
Notarize releases

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#540]
We should start working on getting our releases notarized. The main issue currently is Sparkle. I tried following the [instructions here](https://github.com/sparkle-project/Sparkle/issues/1266#issuecomment-440789584), using the separate branch mentioned, but always got errors about Autoupdate and Updater.app not having the Hardened Runtime enabled.

Maybe we should wait until Sparkle has better support for notarization before notarizing WWDC.app itself.

**Comment by berkcebi** [comment]
Hey @insidegui, we worked around this by codesigning `Autoupdate.app` in a build pre-action run script:
```sh
if [ "${CONFIGURATION}" = "Debug" ]; then
    exit 0
fi

CARTHAGE_BUILD_MAC_DIR="${PROJECT_DIR}/Carthage/Build/Mac"
SPARKLE_AUTOUPDATE_PATH="${CARTHAGE_BUILD_MAC_DIR}/Sparkle.framework/Resources/Autoupdate.app"
codesign --force --deep -o runtime --sign "$CODE_SIGN_IDENTITY" "$SPARKLE_AUTOUPDATE_PATH"
```

…right here in the Scheme editor:
<img width="964" alt="Screen Shot 2019-06-03 at 6 21 32 PM" src="https://user-images.githubusercontent.com/447045/58844548-87690300-862c-11e9-8f1c-822474ba249a.png">

Hope it helps!
