### ISSUE TITLE
macOS Spinning Pinwheel within seconds on launch

### ISSUE THREAD

**Issue by ajtruex** [insidegui/WWDC#547]
macOS Mojave 10.14.5
WWDC 6.1.2
Nothing out of the ordinary is going on with my laptop as I am and have been running applications all day.
Opened the app to check the WWDC schedule for next week and it immediately went to the spinning pinwheel. I then had to force quit the app because I had waited a few minutes without any changes. I repeated this process 3-4 times including uninstalling and redownloading the application from the website with the same exact results.
[Sample of WWDC.txt](https://github.com/insidegui/WWDC/files/3241192/Sample.of.WWDC.txt)

Kind of a postscript here but I thoroughly enjoy the application and have used it for the last few years to not only watch the WWDC but also to use the transcripts you provide and the playback speed adjustability to sit and learn the latest things going on with Apple. I find your platform far superior to the unorganized mess of videos that Apple puts out that can only be watched on Safari and have little to no playback controls so I wanted to thank you for making a quality product even though a trillion dollar company can't.

**Comment by allenhumphreys** [comment]
@ajtruex Could you check https://github.com/insidegui/WWDC/issues/544 to see if you have a similar issue? The problem there was around having a custom downloads directory set.
