### ISSUE TITLE
Full screen not showing full screen video.

### ISSUE THREAD

**Issue by dbarros** [insidegui/WWDC#552]
I am on macOS 10.15.5, and WWDC latest version 6.1.2.

When the app is in full screen mode, would it be possible to have just the video be in full screen? Unless I'm not seeing how it's done, there's not much point in having a full screen mode in a video app if it's not the video itself which is playing and taking over the whole screen.

This is what I see in full screen mode at the moment:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/1286/58923441-1c7e1000-8783-11e9-8ef6-175d78099b71.png">

**Comment by allenhumphreys** [comment]
To put the video player into full screen by itself, use this button:
<img width="1471" alt="Screen Shot 2019-06-04 at 8 18 24 PM" src="https://user-images.githubusercontent.com/8225090/58923619-fe25ff00-8705-11e9-8643-c8f72ebc7ff6.png">

**Comment by dbarros** [comment]
@allenhumphreys I'm sorry that I didn't see that earlier. Just checked now and the reason I didn't is because it doesn't show up when the app is in full-screen mode. Thanks.

**Comment by insidegui** [comment]
You can also double-click the video to move it to fullscreen.

**Comment by klaas** [comment]
Is there also a keyboard shortcut? 

Cmd-F, Globe-F only make the App Window full screen, but not the video player.

(Great App, still better than the Developer app to watch the sessions :-) )
