### ISSUE TITLE
Need to restart app to see if new videos are available

### ISSUE THREAD

**Issue by Urkman** [insidegui/WWDC#555]
There is no way to update the list. So I need to restart to see if new videos are available...

**Comment by DD-P** [comment]
Try switching on **Preferences | Refresh Schedule and Videos periodically**.  The help balloon suggests that it will refresh "every five minutes (useful during WWDC week)".

**Comment by allenhumphreys** [comment]
You can use cmd + R. There’s also a button in the menus.

**Comment by bcmn** [comment]
Like Allen said, I'm not sure what would UI changes help emphasise this -- I think we've already aimed to match similar patterns elsewhere. 

Perhaps this is partially a signal that the five minutes refresh is too long -- Allen & I actually had a brief chat yesterday where I was unsure if the timer had stopped or something, which might add to that.

**Comment by insidegui** [comment]
Closing this since it’s not really an issue. If you have any suggestions about how this could be improved, open a feature request. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
