### ISSUE TITLE
Feature Request: Add toggling/hide-unhide support in Videos tab for Sections like Featured/Design/Frameworks/etc

### ISSUE THREAD

**Issue by ygit** [insidegui/WWDC#556]
- There are many videos under sections like Featured/Design/Frameworks/etc on the Videos Tab
- Scrolling through that huge list of videos requires scrolling vertically a lot
- The section headers should be able to hide/unhide the videos under that section on clicking the header
<img width="1355" alt="Screenshot 2019-06-06 at 1 26 29 pm" src="https://user-images.githubusercontent.com/8512357/59016559-237a5080-885f-11e9-99e4-6dd5f00255ac.png">

**Comment by allenhumphreys** [comment]
This feature essentially exists in the "Filter" area

**Comment by insidegui** [comment]
Closing since filters can be used for, well, filtering. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
