### ISSUE TITLE
WWDC 6.1.2, Realm crashes on macOS 10.15 (19A471t)

### ISSUE THREAD

**Issue by deszip** [insidegui/WWDC#557]
macOS 10.15 Catalina, app crashes right after the launch inside Realm framework. Building it from source using WWDC target doesn't crash, I suppose smth wrong with Realm <-> iCloud integration.

Please see attached log.
[wwdc.log](https://github.com/insidegui/WWDC/files/3260591/wwdc.log)

**Comment by insidegui** [comment]
Working fine here on Catalina. Not sure if OS version is the culprit. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ludagoo** [comment]
It is crashing after updating to Catalina for me too... what info can I collect to help with this?

**Comment by ludagoo** [comment]
oh I'm on 5.3... I thought I downloaded the latest a few days ago

I deleted all realm files in /Users/lucasgoossen/Library/Application Support/io.wwdc.app. after doing that it launched enough to be able to tell me I was on an old version? Tho I'm fairly certain I downloaded most recent a few days ago. Maybe the missing realm files triggered the update dialogue?

**Comment by ludagoo** [comment]
Application Specific Information:
fatal error: Realm initialization error: Error Domain=io.realm Code=2 "Unable to open a realm at path '~/Library/Application Support/io.wwdc.app/ConfCore.realm': Unsupported Realm file format version." UserInfo={Error Code=2, NSFilePath=~/Library/Application Support/io.wwdc.app/ConfCore.realm, Underlying=Unsupported Realm file format version, NSLocalizedDescription=Unable to open a realm at path '~/Library/Application Support/io.wwdc.app/ConfCore.realm': Unsupported Realm file format version.}: file /Users/inside/Developer/_projects/WWDC/WWDC/AppCoordinator.swift, line 62

**Comment by insidegui** [comment]
Thats a VERY old version. You’ll have to delete your realm database and reinstall the latest version without running the old one

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
