### ISSUE TITLE
Still consuming network traffic when the stream is paused or ended

### ISSUE THREAD

**Issue by wangguan1** [insidegui/WWDC#559]
Not sure this is really an issue. I was watching the stream under a very slow network connection(about 2-3 mbps). So this is pretty noticeable.

Screenshot when watching of 2019 sessions.
![image](https://user-images.githubusercontent.com/1572803/59072620-1b7ada80-8878-11e9-8a89-6352265648d7.png)

//----
mojave 10.14.5
build 6.1.2

**Comment by insidegui** [comment]
We don't control when the app is or isn't downloading the video stream, that's handled by AVFoundation.
