### ISSUE TITLE
dual monitor - video controls always showing

### ISSUE THREAD

**Issue by navaler** [insidegui/WWDC#560]
- Version of macOS
macOS Mojave 10.14.5 (18F132)

- Version of the app
6.1.2

- What were you trying to do when the issue happened
Watch a video on second display and working on the primary display

- Any particular hardware/software configuration you have that might be affecting the app
nope

- If it is a crash, please provide the crash log
nope

- If it is a hang (beach ball), please provide a process sample
nope

- If it is a wrong behavior, list all steps required to reproduce it
*Open app on second display
*start video (normal view or fullscreen)
*click on the primary display to active the app you will work in (safari as example)
*Video controls show up after clicking another app and will stay. disappear only if you active the app again and move the cursor over the video player

**Comment by allenhumphreys** [comment]
Duplicates #538
