### ISSUE TITLE
Download videos in destination folder rather than moving it

### ISSUE THREAD

**Issue by alessaba** [insidegui/WWDC#562]
It would be nice if instead of downloading videos in a cache folder and then moving it, the app would download the file directly in the destination folder

Why, you may ask

i have a external SSD on which I have a 40GB partition for the latest beta of macOS Catalina (yes, I know it's very little, my bad)
and a 460GB partition for data.

i set the destination folder for videos in my Data partition, but the app first downloads it to the 40GB partition and then moves it. 

Well... I downloaded like 15 sessions and without noticing the disk space got insanely low on the 40GB partition. so now I have to download the sessions one by one so they don't fill up the entire disk (After downloading the disk space is freed because the file is moved to the Data partition)

Thanks in advance :)
### Before opening your issue, please make sure you answer YES to all of the questions below.

- Are you running the latest version of the app? Yes
- Are you running a release, stable version of macOS? No, but does not matter in this case
- Have you looked at previous issues to see if you're having an issue that's already being worked on? Yes
- If your issue is about compilation or project setup, have you followed the instructions from the readme? Not applicable
- Have you read the Code of Conduct, and will you uphold it's values? Yes

### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS: Catalina Beta 1
- Version of the app: 6.1.2
- What were you trying to do when the issue happened: Downloading Session videos
- Any particular hardware/software configuration you have that might be affecting the app
- If it is a crash, please provide the crash log
- If it is a hang (beach ball), please provide a process sample
- If it is a wrong behavior, list all steps required to reproduce it: I listed them above
- Please add screenshots if you think they might help us diagnose the issue

**Comment by insidegui** [comment]
We use the standard URL session downloading mechanism which uses a temporary folder by default. I'm not sure if it's possible to change its behavior.

**Comment by allenhumphreys** [comment]
Support for this does not appear to be in `URLSession`'s download task API.

**Comment by cameroncooke** [comment]
I second this feature request, had exactly the same issue ran out of disk space on my system drive even though I've got the app set to download to external hdd.

**Comment by insidegui** [comment]
I think the best approach here would be to implement #525 and maybe warn when the disk space seems too low for the amount of content being downloaded, since we don't plan on moving away from the `URLSession` API we're currently using.
