### ISSUE TITLE
Some WWDC 2019 sessions not showing up in list.

### ISSUE THREAD

**Issue by pcolton** [insidegui/WWDC#566]
Running on Catalina, app version 6.1.2, not all the WWDC 2019 sessions are showing up. For example, "Window Management in Your Multitasking App" (session 246), is among some of them NOT showing up in the WWDC app. I've refreshed as well. 

I'm going off this list: https://developer.apple.com/videos/play/wwdc2019

**Comment by insidegui** [comment]
The video you mentioned shows up here.

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/67184/59212027-bda40680-8b87-11e9-8f97-b9de6d386cfb.png">

**Comment by insidegui** [comment]
@pcolton Are you sure you weren't searching in the "Schedule" tab? Video-only sessions won't show up there.

**Comment by mluisbrown** [comment]
@insidegui I'm having the same issue. Session 408 "Adopting Swift Packages in Xcode" is not showing up for me:

![image](https://user-images.githubusercontent.com/4175766/59257474-eb438b00-8c2d-11e9-936b-22dbd8b98972.png)

Although the session that @pcolton doesn't see *is* showing up for me.

**Comment by allenhumphreys** [comment]
@mluisbrown  I'd have to say the most likely culprit is stale data. The doesn't refresh it's data automatically by default. So if you have the app open for a long period of time (white dot under the dock icon) you can miss out on changes that apple publishes.

Just to make sure no assumptions are missed. Please quit the app entirely (cmd + q) and relaunch it _while connected to the internet_ to make sure a data refresh happens. This flow is the most certain to update data. You can additionally enable the period refresh in preferences or manually refresh with cmd + r

**Comment by insidegui** [comment]
> You can additionally enable the period refresh in preferences or manually refresh with cmd + r

The periodic refresh is only active during WWDC week. We should probably tweak it to stay active for a few more days after the week ends.

**Comment by pcolton** [comment]
The videos are showing up now. 🤷🏼‍♂️ Thanks.
