### ISSUE TITLE
Auto-delete watched videos

### ISSUE THREAD

**Issue by Blackjacx** [insidegui/WWDC#567]
It would be cool to provide an option in the settings to auto-delete watched session videos so they do not clutter up disk space.

# Specs
- Version of macOS: 10.14.5
- Version of the app: 6.1.2

**Comment by insidegui** [comment]
Removing the "Good first issue" tag since as it turns out, this is not as simple as it sounds 😅 (Developing in #570).

**Comment by bcmn** [comment]
Closed #570 as I'm not likely to revisit it immediately. Just to capture...

• Needs toggle in Preferences
• Must respect existing "watched" definition, used for filters, etc.
• Should probably sweep for watched videos on first enabling
• Avoid deleting newly-watched videos until player torn down -- but we don't have a stop state for videos, which makes this a little tricky
• Should probably delete immediately if "mark as watched" used

There's some interesting obstacles in the code to get around to achieve these.
