### ISSUE TITLE
Removing a Favorite does not sync to other Macs

### ISSUE THREAD

**Issue by gtriisd** [insidegui/WWDC#569]
macOS 10.14.5
WWDC Version 6.1.2
The action "Add to Favorites" syncs via iCloud to my other Mac, but "Remove from Favorites" does not sync. Not a huge deal, but would be a nice-to-have feature.

**Comment by allenhumphreys** [comment]
Does this relate to #495?

**Comment by insidegui** [comment]
Assuming this is the same as #495
