### ISSUE TITLE
Improve colour contrast on Playback progress indicator

### ISSUE THREAD

**Issue by bcmn** [insidegui/WWDC#572]
There are three colours in the playback progress indicator -- the current time, the hovered time, & the background colour. The WCAG contrast ratio (not normally applied to two non-font elements, but 🤫) doesn't pass on simply the current + background colour, never mind the intermediary hover colour.

<img width="170" alt="Screenshot 2019-06-12 at 22 26 44" src="https://user-images.githubusercontent.com/11646957/59387514-432ede80-8d61-11e9-9291-f6f187b66885.png">

I suggest we increase the contrast between these elements to increase legibility.

**Comment by negna1** [comment]
If this issue is still open i would like to work on that.

**Comment by insidegui** [comment]
@negna1 Absolutely! PR welcome :)
