### ISSUE TITLE
MacOS standard Ctrl-Click should work for context menu

### ISSUE THREAD

**Issue by chrislconover** [insidegui/WWDC#573]
### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS: 10.15
- Version of the app: 6.1.2
- What were you trying to do when the issue happened:
    Mark session as read

- If it is a wrong behavior, list all steps required to reproduce it:

What happened:
Trying to use the Mac OS standard approach of Ctrl-Click for context menu does not work.

What did happen:
Only a two finger click summons the context menu.  I was hours into the using the app, was frustrated with anther bug in which watched sessions were not recorded as such, and was hoping for a way to mark watched sessions as watched. To be sure it wasn't my keyboard, I double checked with the keyboard viewer, and again with a browser to make sure there wasn't some change in the routing of secondary-click messages

What should happen:
The WWDC app should support both modes for control-click: two finger tap, and Ctrl-Click (as is the case for every other Mac app that I have tried).

How to reproduce:

Open app, hover over left / index column, hold down control and tap the trackpad.  Nothing happens.  Only doing a double-tap with a trackpad seems to work.

Great app though - thanks!

**Comment by subdan** [comment]
@insidegui Hey, Rambo. I want to fix this feature. Can I do it as a part of Hacktoberfest 2019?

**Comment by insidegui** [comment]
@subdan Feel free, PRs welcome 😃

**Comment by insidegui** [comment]
I haven't been able to reproduce this on the latest version in macOS 10.15.4. Are any of you able to reproduce this @bcmn @allenhumphreys ?

**Comment by insidegui** [comment]
Closing since we haven't been able to reproduce the issue in recent versions of the app. Please let us know if you have reproducible steps in version 7.1.
