### ISSUE TITLE
Mark as watched / unwatched context menu item should reflect current watched / unwatched state

### ISSUE THREAD

**Issue by chrislconover** [insidegui/WWDC#575]
- Version of macOS: 10.15
- Version of the app: 6.1.2

What happened:

When using the context menu for a session in the index view, the context menu shows options for both: "mark session as watched"  and "mark session as unwatched" for new, never visited states.  

What should happen:

In general, since we are assuming a binary watched / unwatched state, this should be reflected in the *context* menu with only the option that is logically possible.  For example, for a new session, the only logical state is unwatched, so there should not be an option for "mark as unwatched".

Thanks!

**Comment by insidegui** [comment]
We are happy with the way this menu behaves currently, with options that enable/disable themselves based on the currently selected items.
