### ISSUE TITLE
ConfCore.realm is huge

### ISSUE THREAD

**Issue by bartzy** [insidegui/WWDC#578]
- Version of macOS: 10.14.2
- Version of the app: 6.1.2

Hi,

My ConfCore.realm file is 4.8GB. ImageCache.realm file is also ~400MB.
How can I rebuild the database (or just bring the file size down) without losing my favorites, watched, etc?

Thanks!

**Comment by bcmn** [comment]
This definitely sounds unusual -- mine is significantly smaller. It'd be good to establish whether there's some unusual behaviour going on -- would you mind sharing it with us somewhere?

**Comment by bartzy** [comment]
@bcmn Can you perhaps let me know what to look for and I'll try to take a look?

**Comment by bcmn** [comment]
The image cache is pretty believable to me. I'd mainly be looking at ConfCore -- & at this size I'm mainly worried there'll be some duplication going on, so even just working out which type of records (Realm Studio calls them "classes") are making up the bulk of the file would be useful as an initial hint. I'll compare the values to what I would expect in more typical versions of the file.

**Comment by bartzy** [comment]
The TranscriptAnnotation table has 393492 entries. Maybe that's the culprit?

**Comment by bcmn** [comment]
Yeah, but TranscriptAnnotation almost always has the most entries -- there's just far more lines of dialog that anything else. I'm not sure that number is actually particularly unexpected. Can you screenshot the overall values?

**Comment by bartzy** [comment]
Sure:

https://user-images.githubusercontent.com/167339/61777150-21675380-ae05-11e9-9315-fbd64dada50a.png
https://user-images.githubusercontent.com/167339/61777173-2a582500-ae05-11e9-8d43-1c2d7f1829d2.png

**Comment by insidegui** [comment]
BTW there's a way to "compact" a Realm file. I tried implementing an automated way of doing that but it was too flakey to ship. Maybe we could offer a manual way of doing it.

**Comment by bartzy** [comment]
Awesome. I opened the `ConfCore.realm` file in Realm Studio, saved it, it created a 65MB file instead of the 4.8GB one. I replaced the old file with the new one and everything seems to work well.

Thanks!

**Comment by insidegui** [comment]
It probably did the compacting thing I mentioned. @bcmn let's brainstorm how we could integrate this into the app itself. Let's brainstorm in #580

**Comment by sebastienboisvert** [comment]
Still happens in the latest release - left the app running in the background over several days, eventually ate up all my free harddrive space with the `ConfCore.realm` file taking up over 95GB of space:
<img width="716" alt="WWDC app eating up all free space" src="https://user-images.githubusercontent.com/6633750/163688567-332504f4-9dc3-44ba-847e-3e357b846678.png">
