### ISSUE TITLE
Database compression

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#580]
As described in #578, the ConfCore.realm file can get quite big. Realm offers a way to re-save a database file in a way that compresses it. I remember trying to do this automatically a long time ago but having trouble getting it to work reliably.

Maybe something changed that would allow us to implement this now, or at least offer a manual way for the user to do so that doesn't require downloading another piece of software.

**Comment by bcmn** [comment]
There's some intriguing [Realm docs about larger-than-expected Realm files](https://realm.io/docs/swift/latest/#limitations-file-size), especially around accessing while using GCD. I've not had a chance to work out if any of these might be describing what's happening here.

I've seen some fairly "nuclear option" implementations of forcing a re-compression, where people will write another realm file and swap it out. 😶

**Comment by insidegui** [comment]
I believe the `shouldCompactOnLaunch` thing is what I tried before and it caused an awful hang when launching the app. We could try it again to see if it's better now tho.

**Comment by bcmn** [comment]
🤔 Interesting, okay.

**Comment by mackuba** [comment]
@insidegui I've just been comparing some Time Machine snapshots to see why it sometimes needs to back up more than I would expect, and I found an interesting file in the diff - a `~/Library/Application Support/io.wwdc.app/ConfCore.realm` weighing 38.65 GB… this is not normal, is it? 😬

**Comment by insidegui** [comment]
We've had some builds in the past that entered sync loops, causing the database file to grow in that way. If you've been using the app for a long time, it's possible you were affected. Unfortunately, there's no easy solution I can recommend besides just nuking your database file and starting over :/

**Comment by mackuba** [comment]
What do I lose if I do that?

**Comment by insidegui** [comment]
Favorites, bookmarks and video progress (watched/unwatched). The rest is downloaded from the service.

**Comment by mackuba** [comment]
So favorites and watched status aren't synced between computers?

**Comment by insidegui** [comment]
They are. If you’re using iCloud sync, they should be restored. Keep a copy of the original db file just in case.

**Comment by mackuba** [comment]
Ok, thanks 👍

**Comment by insidegui** [comment]
Handled in #596 

Let us know how it goes for your database @mackuba. I expect it may hang the first time you launch the app with this enabled, but afterwards it should be fine.

**Comment by insidegui** [comment]
Just FYI: this has been temporarily disabled in version 7.1 as we wait for Realm to fix https://github.com/realm/realm-cocoa/issues/6652
