### ISSUE TITLE
WWDC app not synced across mac computers

### ISSUE THREAD

**Issue by yoasha** [insidegui/WWDC#582]
I have two macs with this great app, while sync is enabled, but some how the apps went out of sync. What is the recommended method to reset the sync data on iCloud and start syncing from scratch?

BTW, where is WWDC sync data is located on iCloud? How can I remove it from iCloud? The usual location of System Preferences > iCloud > Manage, is not showing WWDC.

**Comment by insidegui** [comment]
@yoasha There is a previous bug you filed for the same issue: https://github.com/insidegui/WWDC/issues/509

**Comment by yoasha** [comment]
Thank you for pointing out issue #509 and sorry for opening a new issue on the same topic.

I'm reading the #509 history and see something about that my WWDC iCloud zone was deleted. I'm an iOS developer and keep my app's data in iCloud container. If anything goes wrong, I'm guiding my customers to simply delete the app data at Settings > iCloud > Manage and my app will create it again. I never encountered any zone related issue in iOS. Is this something specific to macOS? Why is WWDC app isn't creating the app container if it's not there. What is the difference between my case and the case that the app was first installed and executed?

**Comment by yoasha** [comment]
I just wish to workaround the issue and clear any leftovers of the WWDC iCloud sync data manually, if that is possible. Is it?

**Comment by insidegui** [comment]
This is a bug in the WWDC app we haven't fixed yet, where it won't re-create the zone if it was deleted, as I mentioned here: https://github.com/insidegui/WWDC/issues/509#issuecomment-429351485

Closing as a duplicate.
