### ISSUE TITLE
Ability to filter for Non-Downloaded videos.

### ISSUE THREAD

**Issue by luvvie** [insidegui/WWDC#583]
Hopefully this desired functionality can adequately be described as being the opposite of what the 'Downloaded' filter provides. Essentially displaying what videos have not yet been been download, allowing one to hone in on what videos may want to be added to the download queue.

This would be in addition to the existing downloaded indicator within each list cell, and would most likely (hopefully) have no bearing on this nicety.

**Comment by davedelong** [comment]
+1 I would love this 🥺
