### ISSUE TITLE
Add session resource index to make app could play the disappeared videos

### ISSUE THREAD

**Issue by MainasuK** [insidegui/WWDC#594]
It looks like Apple remove some WWDC videos from the website. For example, there are only dozens of videos on the [WWDC 2014](https://developer.apple.com/videos/play/wwdc2014) list. 

And here is a [gist](https://gist.github.com/jianpx/eea1e938d5868e980b11) for the resources for WWDC 14. I can play the WWDC 14 session 714 directly from the video [URL](http://devstreaming.apple.com/videos/wwdc/2014/714xx1h4szxdnyz/714/714_hd_fix_bugs_faster_using_activity_tracing.mov?dl=1
). But no session page on the path at https://developer.apple.com/videos/wwdc/2014/?id=714. The WWDC.app also can not search that session.

I have no idea why Apple removes the sessions. Can we index the session resources in the repo to make the app able to play the missing session?

Thanks.

**Comment by insidegui** [comment]
Sorry, we have no intention in displaying content that's been removed from Apple's API. Maintaining two separate data sources would be a huge source of complexity and is really bug-prone. If you need to consume that old content, I suggest browsing it directly from the sources you mentioned.
