### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by mirkoevo** [insidegui/WWDC#616]
### Before opening your issue, please make sure you answer YES to all of the questions below.

- Are you running the latest version of the app? YES
- Are you running a release, stable version of macOS? YES
- Have you looked at previous issues to see if you're having an issue that's already being worked on? YES
- If your issue is about compilation or project setup, have you followed the instructions from the readme? YES
- Have you read the Code of Conduct, and will you uphold it's values? YES

### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS
10.15.5

- Version of the app
Your latest build, but also previous versions had this problem. Randomly it starts crashing at startup and I have to manually check or remove some realm databases in or intermediary files.

% ll ~/Library/Application\ Support/io.wwdc.app/
total 491528
drwxr-xr-x    8 staff        256 Jun 16 07:59 ./
drwx------+ 459 staff      14688 Jun 15 12:41 ../
-rw-r--r--    1 staff  134217728 Jan 22  2019 ConfCore.realm
-rw-r--r--@   1 staff       1184 Jun 16 08:05 ConfCore.realm.lock
drwxr-xr-x@   6 staff        192 Dec 20  2018 ConfCore.realm.management/
-rw-r--r--    1 staff  117440512 Jan 22  2019 ImageCache.realm
drwxr-xr-x@   6 staff        192 Dec 20  2018 ImageCache.realm.management/
drwxr-xr-x    3 staff         96 Dec 20  2018 com.crashlytics/

- What were you trying to do when the issue happened
Just launch the app

- Any particular hardware/software configuration you have that might be affecting the app
No

- If it is a crash, please provide the crash log

Process:               WWDC [62260]
Path:                  /Applications/WWDC.app/Contents/MacOS/WWDC
Identifier:            io.wwdc.app
Version:               7.0.2 (1003)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           WWDC [62260]
User ID:               501

Date/Time:             2020-06-16 08:05:51.571 +0200
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        4BECA090-AA25-6F99-47D9-AA67E44C8F05

Sleep/Wake UUID:       07380C52-7E72-4AD9-870F-2A3952DAE67B

Time Awake Since Boot: 630000 seconds
Time Since Wake:       1700 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [62260]

Application Specific Information:
Fatal error: Realm initialization error: Error Domain=io.realm.unknown Code=13 "Permission denied" UserInfo={Category=system, NSLocalizedDescription=Permission denied, Error Code=13}: file /Users/inside/Developer/_projects/WWDC/WWDC/AppCoordinator.swift, line 80
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	0x00007fff6b65a30f _assertionFailure(_:_:file:line:flags:) + 863
1   io.wwdc.app                   	0x000000010791573c 0x1078a9000 + 444220
2   io.wwdc.app                   	0x0000000107939a28 0x1078a9000 + 592424
3   com.apple.AppKit              	0x00007fff2f2dd6f2 -[NSClassSwapper initWithCoder:] + 1156
4   com.apple.Foundation          	0x00007fff3464ba00 _decodeObjectBinary + 2684
5   com.apple.Foundation          	0x00007fff3464ae60 _decodeObject + 260
6   com.apple.Foundation          	0x00007fff3464acf4 -[NSKeyedUnarchiver decodeObjectForKey:] + 139
7   com.apple.AppKit              	0x00007fff2f24b511 -[NSNibConnector initWithCoder:] + 89
8   com.apple.AppKit              	0x00007fff2f24b454 -[NSNibOutletConnector initWithCoder:] + 414
9   com.apple.Foundation          	0x00007fff3464ba00 _decodeObjectBinary + 2684
10  com.apple.Foundation          	0x00007fff3464d4e4 -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 829
11  com.apple.Foundation          	0x00007fff34665572 -[NSArray(NSArray) initWithCoder:] + 176
12  com.apple.Foundation          	0x00007fff3464ba00 _decodeObjectBinary + 2684
13  com.apple.Foundation          	0x00007fff3464ae60 _decodeObject + 260
14  com.apple.Foundation          	0x00007fff3464acf4 -[NSKeyedUnarchiver decodeObjectForKey:] + 139
15  com.apple.AppKit              	0x00007fff2f24a0a1 -[NSIBObjectData initWithCoder:] + 168
16  com.apple.Foundation          	0x00007fff3464ba00 _decodeObjectBinary + 2684
17  com.apple.Foundation          	0x00007fff3464ae60 _decodeObject + 260
18  com.apple.Foundation          	0x00007fff3464acf4 -[NSKeyedUnarchiver decodeObjectForKey:] + 139
19  com.apple.AppKit              	0x00007fff2f2dc337 -[NSNib _instantiateNibWithExternalNameTable:options:] + 512
20  com.apple.AppKit              	0x00007fff2f2dc042 -[NSNib _instantiateWithOwner:options:topLevelObjects:] + 143
21  com.apple.AppKit              	0x00007fff2fa808d9 -[NSStoryboard _instantiateMainMenu:] + 189
22  com.apple.AppKit              	0x00007fff2f23ab1d NSApplicationMain + 672
23  libdyld.dylib                 	0x00007fff6bffecc9 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff6c1feb68 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff6c1feb68 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff6c1feb68 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x00007fff6c1feb68 start_wqthread + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000200000002  rbx: 0x000060000274c460  rcx: 0xfffffffe00000000  rdx: 0x0000000000000002
  rdi: 0x000060000274c468  rsi: 0x00007fc20e400000  rbp: 0x00007ffee8355920  rsp: 0x00007ffee83558d0
   r8: 0x000000000000049d   r9: 0x000000000000003b  r10: 0x00007fc20e400000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0xe000000000000002  r15: 0x000000010799df80
  rip: 0x00007fff6b65a30f  rfl: 0x0000000000010246  cr2: 0x00007fff9277f640
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     6

**Comment by insidegui** [comment]
Already covered in #613
