### ISSUE TITLE
Clip sharing doesn't work in the schedule tab

### ISSUE THREAD

**Issue by insidegui** [insidegui/WWDC#618]
I have been able to verify that this issue is being caused by `viewModel` being `nil` in line 133 of the `ShelfViewController`. I haven't been able to find the root cause yet.

**Comment by BrianBatchelder** [comment]
I was looking at the same thing. It works in the "Videos" tab, but not the "Schedule" tab.

**Comment by insidegui** [comment]
Thanks for pointing that out, I completely forgot about the Videos tab for a moment here 😅
