### ISSUE TITLE
Clipped video is not sized correctly

### ISSUE THREAD

**Issue by BrianBatchelder** [insidegui/WWDC#622]
### Before opening your issue, please make sure you answer YES to all of the questions below.

- Are you running the latest version of the app? ***YES***
- Are you running a release, stable version of macOS? ***YES***
- Have you looked at previous issues to see if you're having an issue that's already being worked on? ***YES***
- Have you read the Code of Conduct, and will you uphold it's values? ***YES***

### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS ***10.15.5***
- Version of the app ***7.0.2***
- What were you trying to do when the issue happened ***Clip from a WWDC video***
- Any particular hardware/software configuration you have that might be affecting the app ***Unknown***
- If it is a wrong behavior, list all steps required to reproduce it ***Clip from a WWDC video. View clip.***
- Please add screenshots if you think they might help us diagnose the issue

![image](https://user-images.githubusercontent.com/2123928/85633138-79b65f00-b62d-11ea-89d7-7a51fb906c9c.png)

Here's the actual clip:
[Design great app clips-614728534.mp4.zip](https://github.com/insidegui/WWDC/files/4828115/Design.great.app.clips-614728534.mp4.zip)

**Comment by insidegui** [comment]
Already dealt with in #621

**Comment by BrianBatchelder** [comment]
Thanks!
