### ISSUE TITLE
Bottom of screen not visible on 1366 x 768 displays

### ISSUE THREAD

**Issue by tarasis** [insidegui/WWDC#623]
### Before opening your issue, please make sure you answer YES to all of the questions below.

- Are you running the latest version of the app? -- **Yes**
- Are you running a release, stable version of macOS? -- **Yes**
- Have you looked at previous issues to see if you're having an issue that's already being worked on? Yes
- If your issue is about compilation or project setup, have you followed the instructions from the readme? -- using prebuilt version
- Have you read the Code of Conduct, and will you uphold it's values? -- **Yes**

### If you answered YES to all of the questions, please provide as much information as possible about your issue.

When running the app on a 1366 x 768 display, the bottom of the app is chopped off. You can only just see the tops of the Related Sessions. While it is possible to resize the app horizontally, you can not resize vertically, nor can you scroll the session view.

This the how the app looked zoomed to fill the screen. You can see at the bottom the related sessions are chopped. 
![WWDC App Zoomed](https://user-images.githubusercontent.com/3006/85748123-beaac600-b6ff-11ea-8088-a579025bfdfc.png)

If you then swap to full screen, you can now see all the related sessions, but the top of the video is chopped off.
![WWDC App Full Screen](https://user-images.githubusercontent.com/3006/85748096-bb173f00-b6ff-11ea-97f3-18e4a9c4e56d.png)

- Version of macOS -- **10.15.5**
- Version of the app -- **7.0.2**
- What were you trying to do when the issue happened

Just running the app normally

- Any particular hardware/software configuration you have that might be affecting the app

Running app on 11" MacBook Air, its res is 1366 x 768

- If it is a crash, please provide the crash log
- If it is a hang (beach ball), please provide a process sample
- If it is a wrong behavior, list all steps required to reproduce it

Open app on a 1366x768 screen. 
Select a session.

- Please add screenshots if you think they might help us diagnose the issue

Additional quirk. Sometimes the related sessions aren't visible at all, but if you swipe up into mission control, and then swipe out of it again, the contents resize themselves and the related sessions appear. (However this doesn't work if you use App Expose)

Selected a session, presently the related sessions aren't visible.
![Related Sessions not visible](https://user-images.githubusercontent.com/3006/85749555-dcc4f600-b700-11ea-8d9e-2d375e49053b.png)

After using Mission Control (swipe 3 fingers up, then either swipe 3 fingers down, or just click on the window), the contents resize slightly and the related sessions are visible.

![Related Sessions visible after using Mission Control](https://user-images.githubusercontent.com/3006/85749561-dd5d8c80-b700-11ea-8371-c94518bcd5a0.png)

**Comment by allenhumphreys** [comment]
The good news here is we've moved to a scroll view for the session summary. This keeps the maximum window height to 733 pixels. This hopefully will just barely squeeze into your display. Any chance you could confirm via building master directly?

**Comment by tarasis** [comment]
I can build it, just might take a while on this thing. will report back later and thanks for the swift reply.

**Comment by insidegui** [comment]
I had the same issue, which prompted #617, so this has already been fixed 🥳
