### ISSUE TITLE
Playback Speed: add shortcut keys for changing playback speed

### ISSUE THREAD

**Issue by muescha** [insidegui/WWDC#626]
### Where

- while playing a video 

### What i do

- i often change the speed to skip not important parts 
- i often then like to fast change the speed to normal speed to understand details

### What i expect

- i like to adjust the speed with keyboard shortcuts

### what i see 

- i can right click but i need to choose in a select list: then still it takes time to select the speed
- i can click, but then it not changes between my prefered speed - it always cycle through all settings: this takes also to much time to select my speed

### others

- on YouTube i can adjust the speed with `<` and `>`

**Comment by insidegui** [comment]
Hi, you can use the `+` and `-` keys, which are already implemented. There is also a button in the Touch Bar.

**Comment by muescha** [comment]
a) my macbook not have a touch bar
b) the buttons are not documented

i suggest:
1) add shortcuts to repo readme
2) add info about shortcuts as quicktip while hover over the speed button

**Comment by insidegui** [comment]
Feel free to open a pull request with those additions :)
