### ISSUE TITLE
WWDC 2014 Swift Sessions missing

### ISSUE THREAD

**Issue by masters3d** [insidegui/WWDC#629]
### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS 10.15.5
- Version of the app 7.0.2
- What were you trying to do when the issue happened n/a
- Any particular hardware/software configuration you have that might be affecting the app n/a
- If it is a crash, please provide the crash log
- If it is a hang (beach ball), please provide a process sample
- If it is a wrong behavior, list all steps required to reproduce it
- Please add screenshots if you think they might help us diagnose the issue

I am noticing that all except for one of the following sessions are missing

Missing:
- 402 Introduction to Swift
- 403 Intermediate Swift
- 404 Advanced Swift
- 406 Integrating Swift with Objective-C
- 407 Swift Interoperability In Depth
- 408 Swift Playgrounds
- 409 Introduction to LLDB and the Swift REPL

This is the only one that shows up
- 410 Advanced Swift Debugging in LLDB

**Comment by insidegui** [comment]
I don't see those sessions in the contents feed, they have probably been pulled by Apple.

**Comment by masters3d** [comment]
Trying to get some traction on this issue on the swift forum as the videos missing are swift related. https://forums.swift.org/t/wwdc-videos-archive/38202/4

**Comment by bcmn** [comment]
I think its safe to close this issue? We're clear we'll render anything that appears in the feed.

**Comment by masters3d** [comment]
Here is the list:

https://gist.github.com/jianpx/eea1e938d5868e980b11
