### ISSUE TITLE
Blank screens for Featured, Schedule, Video sections

### ISSUE THREAD

**Issue by dennisjbr** [insidegui/WWDC#636]
Note: Community tab shows content just fine.

### Before opening your issue, please make sure you answer YES to all of the questions below.

- Are you running the latest version of the app?
YES

- Are you running a release, stable version of macOS?
YES - Catalina

- Have you looked at previous issues to see if you're having an issue that's already being worked on?
YES
- If your issue is about compilation or project setup, have you follo
wed the instructions from the readme?
N/A
- Have you read the Code of Conduct, and will you uphold it's values?
YES

### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS
10.15.6
- Version of the app
7.1
- What were you trying to do when the issue happened
Start for the first time

- Any particular hardware/software configuration you have that might be affecting the app
No. MacBook Pro 16"

- If it is a crash, please provide the crash log
- If it is a hang (beach ball), please provide a process sample
- If it is a wrong behavior, list all steps required to reproduce it
- Please add screenshots if you think they might help us diagnose the issue

![image](https://user-images.githubusercontent.com/2461581/89154308-7dd27800-d51b-11ea-8189-22dd0f4f83c1.png)

![image](https://user-images.githubusercontent.com/2461581/89154366-99d61980-d51b-11ea-80f3-75e17923726f.png)

![image](https://user-images.githubusercontent.com/2461581/89154412-abb7bc80-d51b-11ea-9d9e-6581211b7268.png)

![image](https://user-images.githubusercontent.com/2461581/89154435-b7a37e80-d51b-11ea-98be-ece0476855b5.png)

**Comment by insidegui** [comment]
Hi @dennisjbr! This looks like it could be due to a poorly-handled network failure. Is the app completely stuck in this state or does it populate itself with data if you quit and launch it again?

If it's still the case after a relaunch, it would really help out if you could capture some logs. Quit the app, then run this in Terminal:

```log stream --color always --level debug --style compact --predicate "process contains 'WWDC'" > ~/Desktop/WWDC.log```

After that's running, launch the app and wait a couple of minutes. Press CTRL+C in Terminal to stop capturing the logs. You'll have a `WWDC.log` file in your desktop you can send here so we can check out what's happening.

Thank you

**Comment by klaes-ashford** [comment]
@insidegui please find the logs on a fresh start : 
[WWDC.log](https://github.com/insidegui/WWDC/files/5030132/WWDC.log)
log on subsequent launch: 
[WWDC2.log](https://github.com/insidegui/WWDC/files/5030136/WWDC2.log)

**Comment by insidegui** [comment]
We believe this may have been temporary a server-side issue given the `500` errors seen in the logs. Please let us know if it's still happening or in case it happens again in the future.
