### ISSUE TITLE
Add logic to delete the old image cache Realm

### ISSUE THREAD

**Issue by allenhumphreys** [insidegui/WWDC#639]
We switched away from Realm for the image caching for good reason, but we forgot to delete the Realm files. This can take up a few GB of space!

**Comment by insidegui** [comment]
https://github.com/insidegui/WWDC/blob/2cc0d88c24440b5f817fe459cc3296936e1bdee9/WWDC/ImageDownloadCenter.swift#L79

Maybe you've downgraded during testing, so the `deletedLegacyImageCache` flag was already set? Maybe we could just check for file existence instead of having this flag 🤔

**Comment by allenhumphreys** [comment]
Oh yeah I bet that's absolutely what happened! During release testing I did several down/upgrade combinations.
