### ISSUE TITLE
Is there any way to download SD video files instead of HD ones?

### ISSUE THREAD

**Issue by abbasmousavi** [insidegui/WWDC#64]
Is there any way to download SD video files instead of HD ones?

**Comment by insidegui** [comment]
Not currently. To simplify the interface (and the code) I've decided to only download the HD versions.

**Comment by insidegui** [comment]
I've decided to not implement this since It's not very useful and would complicate things quite a bit.

**Comment by trs123** [comment]
I disagree. Actually I would find it very useful as the HD ones are effectively not usable IMHO to watch demos as code or other details shown in Xcode won't be readable.
