### ISSUE TITLE
Improve bootstrap.sh by checking for Carthage installation

### ISSUE THREAD

**Issue by subdan** [insidegui/WWDC#643]
Hello, @insidegui.

I've run `./bootstrap.sh` and get the following error:
`line 55: carthage: command not found`

I want to add checking for Carthage installation and install it via Homebrew if Carthage not found.
Can I do this as part of Hacktoberfest 2020?

**Comment by insidegui** [comment]
Hi @subdan !

Feel free to improve the script and send a PR.

Thank you
