### ISSUE TITLE
Eggy looking sound control element

### ISSUE THREAD

**Issue by japanese-goblinn** [insidegui/WWDC#660]
- Version of macOS: 11.4
- Version of the app: 7.3.3
- What were you trying to do when the issue happened: Just open the first video.

Tried to fix it myself but failed to build the app without paid developer account 😢

**Actual result**
<img width="137" alt="image" src="https://user-images.githubusercontent.com/33631005/124363081-cf124c80-dc41-11eb-94ba-1382882b920e.png">

**Expected result**
<img width="202" alt="image" src="https://user-images.githubusercontent.com/33631005/124363067-ba35b900-dc41-11eb-8e95-152f19a860d6.png">

**Comment by das-anubhav** [comment]
Hi!
I would like to solve the issue.

**Comment by bcmn** [comment]
Hey @das-anubhav 👋 You're more than welcome -- we'll get any PRs reviewed as & when. 

I've not looked into this much, but it would seem [PUIPlayerView](https://github.com/insidegui/WWDC/blob/7b40c04cdfdce600452e6a22aca347979066812f/PlayerUI/Views/PUIPlayerView.swift#L529-L552) would be the place to start.

**Comment by das-anubhav** [comment]
Hi @bcmn 
The issue is solved now.

**Comment by bcmn** [comment]
Fixed above.
