### ISSUE TITLE
No contents opened in MacBook Pro 2015 intel CPU

### ISSUE THREAD

**Issue by zonebin** [insidegui/WWDC#664]
<img width="1552" alt="截屏2022-06-08 22 07 34" src="https://user-images.githubusercontent.com/14846054/172637710-b27f085d-994f-4f90-81f2-ee21187ac002.png">

- Version of macOS: macOS 12.4 (21F79)

- Version of the app: 7.3.3

**Comment by zonebin** [comment]
- Version of macOS: macOS 12.4 (21F79)

- Version of the app: 7.3.3

**Comment by zonebin** [comment]
First install the App 7.3.3, there is no content.
Then Install 7.2 version, it is all right.
And upgrade to v7.3.3, it is still Ok.

**Comment by insidegui** [comment]
I think it's likely that this was a networking failure. The initial content fetch can be heavy and the servers are being hit a lot during this week. I'll leave the issue opened for now in case others have more to add.

**Comment by insidegui** [comment]
@ohmantics @zonebin A server issue was identified and fixed that was likely the underlying cause for this issue. Could you check if it's addressed for you?

**Comment by zonebin** [comment]
Delete WWDC app, and reinstall v7.3.3, it is OK.
But have installed other version, not sure is OK for the first installation of v7.3.3.
