### ISSUE TITLE
Feat Req: Add `tech-talk`  videos

### ISSUE THREAD

**Issue by Charlotte3240** [insidegui/WWDC#667]
I found some the same important videos than wwdc. you can see it like [this](https://developer.apple.com/videos/play/tech-talks/702/)
this is [home page](https://developer.apple.com/videos/)
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/13010614/230844071-a712818b-094d-4cf1-b8a0-1ad37e10dc3e.png">

**Comment by insidegui** [comment]
Thanks for reporting @Charlotte3240. I had forgotten to point the API to the latest content on Apple's app. You should now see the new content in the WWDC app.
