### ISSUE TITLE
各种报错啊，怎么运行不起来了？

### ISSUE THREAD

**Issue by wy19901227** [insidegui/WWDC#68]

**Comment by insidegui** [comment]
If you are trying to open/compile the project under El Capitan (Xcode 7) you'll see tons of errors. I will continue to develop the app using the stable version of Xcode.

And please ask questions in english if possible. Thanks!

**Comment by wy19901227** [comment]
I  run it in xcode 6.1  it failed also.

**Comment by insidegui** [comment]
Did you pull the dependencies? Check the build instructions on the readme.
