### ISSUE TITLE
Subtitles UI & Status error, V7.4

### ISSUE THREAD

**Issue by BenjaminX** [insidegui/WWDC#685]
![SCR-20230606-evj](https://github.com/insidegui/WWDC/assets/612858/eaf09063-a85b-4e2a-9fbe-952371aeb520)

**Comment by allenhumphreys** [comment]
This was an easy fix, and it's been broken for awhile it seems:

https://github.com/insidegui/WWDC/commit/a9654d530794e54bcc02efe1fc884f85a57a213f#diff-0efb26c215f40ec9b4a5d7427e7bf79e1d0e0340445629b3f9a9930485e0e68cR1070
