### ISSUE TITLE
Way to ignore content without videos

### ISSUE THREAD

**Issue by jcampbell05** [insidegui/WWDC#697]
### Before opening your issue, please make sure you answer YES to all of the questions below.

- Are you running the latest version of the app? yes
- Are you running a release, stable version of macOS? stable
- Have you looked at previous issues to see if you're having an issue that's already being worked on? yes
- If your issue is about compilation or project setup, have you followed the instructions from the readme? yes
- Have you read the Code of Conduct, and will you uphold it's values? yes

### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS 13.3
- Version of the app 7.4.2
- What were you trying to do when the issue happened find videos
- Any particular hardware/software configuration you have that might be affecting the app no
- If it is a crash, please provide the crash log
- If it is a hang (beach ball), please provide a process sample
- If it is a wrong behavior, list all steps required to reproduce it
- Please add screenshots if you think they might help us diagnose the issue

The app is full of Q&As which isn't helpful for people who haven't attened, a feature to filter no-videos would be great!

**Comment by insidegui** [comment]
Thanks for the feedback @jcampbell05 

Is the existing filter in the Schedule tab not enough?
The filter is persisted across app launches (although there seems to be a bug where they can be reset sometimes, I'm investigating).

<img width="352" alt="CleanShot 2023-06-09 at 08 59 22" src="https://github.com/insidegui/WWDC/assets/67184/cf1a4870-f5c4-4dc0-a979-c0cd4031334c">

In the Videos tab, only videos are shown.

**Comment by jcampbell05** [comment]
@insidegui  Ah that's perfect, for some reason the "All Event" just didn't seem like the correct place to find that option.

**Comment by insidegui** [comment]
Yeah, we should probably change the filter title to something like “All Content” instead.
