### ISSUE TITLE
When there's only one video result after filtering, clicking on it does not display it

### ISSUE THREAD

**Issue by JetForMe** [insidegui/WWDC#698]
### Before opening your issue, please make sure you answer YES to all of the questions below.

- Are you running the latest version of the app?
- Are you running a release, stable version of macOS?
- Have you looked at previous issues to see if you're having an issue that's already being worked on?
- If your issue is about compilation or project setup, have you followed the instructions from the readme?
- Have you read the Code of Conduct, and will you uphold it's values?

### If you answered YES to all of the questions, please provide as much information as possible about your issue.

- Version of macOS: 13.4
- Version of the app: 7.4.2
- What were you trying to do when the issue happened: watch a video
- Any particular hardware/software configuration you have that might be affecting the app
- If it is a crash, please provide the crash log
- If it is a hang (beach ball), please provide a process sample
- If it is a wrong behavior, list all steps required to reproduce it
- Please add screenshots if you think they might help us diagnose the issue

I filtered videos for "OpenAPI". There's only one result. When I select it, its details don't replace whatever was selected before in the right-hand pane.

Also, the reason to keep working on this app is it's better than the Developer app. That one really restricts the size of the video playback window.

**Comment by JetForMe** [comment]
Hmm, quitting and relaunching fixed it. I did have a period where it wouldn't show up in the filter at all. Very strange.

**Comment by allenhumphreys** [comment]
@JetForMe it's very possibly related to realm being locked during an update from the backend. We've been discussing app architecture changes to address these issues. The main branch also has a change to optimize the update to decrease the chance of issues.
