### ISSUE TITLE
Add ability to skip forward/back 10s/15s/30s

### ISSUE THREAD

**Issue by mrkd** [insidegui/WWDC#70]
When watching these session videos I usually use VLC's step forward/backward shortcuts to skip forward/backwards if I want to skip or review something within the session video.

Is this something that can be added to the AVPlayer controls ?

**Comment by insidegui** [comment]
Maybe.

**Comment by bddckr** [comment]
On Yosemite I can swipe with two fingers two advance/rewind the video. Clicking on the forward/rewind buttons while holding ⌥ changes the playback speed.

**Comment by insidegui** [comment]
I'm actually rewriting the player portion of the app to be more reliable/customizable.

**Comment by dstd** [comment]
@mrkd for the time being you can try this branch https://github.com/dstd/WWDC/commits/playback-features.
It contains few playback features that I wanted: `float on top`, `playback speed` and `jump backward/forward`, available via `Window` menu.

**Comment by mrkd** [comment]
@dstd - thanks i'll take a look
