### ISSUE TITLE
Feature Request: Filter  by year, platform

### ISSUE THREAD

**Issue by iamcam** [insidegui/WWDC#72]
It would be helpful to be able to filter by year and/or platform.

For example, filter the list so I see...
* Just 2015 videos
* iOS videos
* 2014 iOS videos
* etc

**Comment by bre7** [comment]
You can do it using the search bar:
* Just 2015 videos
 * year:2015
* iOS videos
 * focus:ios
* 2014 iOS videos
 * year:2014 focus:ios

Supported qualifiers are stated in the readme:
> You can perform an advanced search using the qualifiers "year", "focus", "track", "downloaded" and "description".

**Comment by iamcam** [comment]
I'm sorry - I must have missed that part. Thanks!

**Comment by bre7** [comment]
Np.
