### ISSUE TITLE
add speed control 

### ISSUE THREAD

**Issue by kostiakoval** [insidegui/WWDC#85]
The Quick player supports speed control when you click >> and << . 
Also clicking it with "ALT" button allows 1.1, 1.2 speed control which is incredible useful.

Would love to have that feature.

**Comment by insidegui** [comment]
I'm working on a new custom player that will allow me to add some more advanced controls.

**Comment by kostiakoval** [comment]
Great, thanks! sorry for not contributing to the source code :(

**Comment by insidegui** [comment]
No problem :)
