### ISSUE TITLE
Add Google Cast Integration

### ISSUE THREAD

**Issue by justinjdickow** [insidegui/WWDC#86]
Would be amazing to be able to watch these videos with on my TV via Chromecast

**Comment by insidegui** [comment]
I don't know anything about Chromecast. Let's see if others can help...

**Comment by joeljfischer** [comment]
As far as I know the only Google Cast SDKs that exist are iOS, Android, and Chrome.

https://developers.google.com/cast/docs/developers

**Comment by insidegui** [comment]
I think maybe the iOS SDK could be used on the Mac, I haven't looked too far into It. If anyone wants to send me the US$50 for me to purchase a Chromecast and try It, my PayPal e-mail is insidegui@gmail.com :)

**Comment by MaddTheSane** [comment]
@insidegui The ChromeCast SDK for iOS will not work with OS X: The framework file is just a fat ar archive, targeted to only the iOS platform. I tried to "flatten" it out to a dynamic library, but the library ended up being empty.

**Comment by insidegui** [comment]
Ah, I thought It was open source. So yeah, no Google Cast integration for now...

**Comment by bre7** [comment]
Bump

Not sure how but Airflow does it: airflowapp.com

**Comment by insidegui** [comment]
I don't have a Chromecast to test with :/

**Comment by bre7** [comment]
Is there a way to "Open location in Finder" for saved sessions ?

**Comment by insidegui** [comment]
No but you can see/set the path in Preferences.

**Comment by bre7** [comment]
Thanks. So apparently they use a custom library. VLC has plans to add casting to all of their products so I guess they could update https://code.videolan.org/videolan/VLCKit at some point. Airflow is the way to go for now....Why can't Google just publish a library for desktop casting without Chrome 😢

**Comment by insidegui** [comment]
I'm closing this as a duplicate. ChromeCast support will be available on version 5 😉
