### ISSUE TITLE
My Mac goes screen-save mode while watching video.

### ISSUE THREAD

**Issue by EvgenyKarkan** [insidegui/WWDC#95]
Is that normal behaviour and should be managed by me in mac settings or is it WWDC app UX issue?

**Comment by insidegui** [comment]
Which version of OS X are you running? Do you have the latest version of WWDC? I couldn't reproduce this issue on 10.10.4 running the latest version of the app...

**Comment by EvgenyKarkan** [comment]
OS X - v10.10.5 (14F27)
WWDC -  v2.2 (80)

**Comment by insidegui** [comment]
I've added `.UserInitiated` to the list of activity options passed to `beginActivityWithOptions` on `VideoWindowController`, maybe that will prevent the screensaver from activating.

**Comment by insidegui** [comment]
I'm closing this issue since I've had no other complaints and couldn't reproduce the problem myself.

**Comment by sasikiran** [comment]
I currently have this issue on the latest version on Sierra. I have to manually disable screensaver and display sleep while watching videos.

**Comment by jshier** [comment]
Noticed this as well. Version 5.0.6.

**Comment by insidegui** [comment]
This is a known issue that will be fixed with a future update.
