### ISSUE TITLE
Crash while playing video

### ISSUE THREAD

**Issue by vani2** [insidegui/WWDC#96]
I got many crashes on El Capitan during playing video

**Comment by insidegui** [comment]
A crash log would be helpful...

**Comment by haxpor** [comment]
I experienced the same as the original poster of this issue.
I've seen you use Crashlytics too, but anyway this is [my log](https://wasin.io/user-data/wwdc.log) regarding to multiple crashes in it.

**Comment by hellowrcj** [comment]
I'm sorry that It crash just while playing video, I hope the image could help.
<img width="987" alt="screenshot" src="https://cloud.githubusercontent.com/assets/15797115/11931890/30817f68-a82c-11e5-8120-576e40ac00b2.png">

**Comment by insidegui** [comment]
I am currently investigating this issue.

@hellowrcj Thanks, but your screenshot doesn't actually help. If you happen to encounter this issue again, copy the "Problem Details and System Configuration" information and send It here ;)

**Comment by haxpor** [comment]
Lately, after El Capitan is out of beta, I didn't experience the crash again.

**Comment by insidegui** [comment]
@haxpor Thanks for letting me know.

Now I've noticed @hellowrcj is running 10.10.5, I don't pay too much attention to old OS crashes. Since this app is aimed at developers, I only worry about It running well on the latest stable release of OS X.

**Comment by hellowrcj** [comment]
My mac is on OS X Yosemite Version 10.10.5, this is info  [Problem Details and System Configuration](http://7xl4rd.dl1.z0.glb.clouddn.com/CrashLog.pdf) while crashing.Maybe I need update my OS.

**Comment by haxpor** [comment]
@insidegui I'm on 10.11.1 (15B42).
