### ISSUE TITLE
Grouping videos by WWDC Session

### ISSUE THREAD

**Issue by flexaddicted** [insidegui/WWDC#99]
It could be useful to have videos grouped by sessions using sections.

**Comment by insidegui** [comment]
Maybe ;)

**Comment by lmihalkovic** [comment]
Personally I like to group them by year. 

<img width="374" alt="screen shot 2016-02-24 at 1 12 53 pm" src="https://cloud.githubusercontent.com/assets/1318077/13285027/7cffdc78-daf8-11e5-8c56-bd3b98a63ddb.png">

Would it be ok to add another button to decide on a grouping strategy? (session, year, other?). If that is the case, maybe some graphic showing alternating horizontal bars with some thicker to convey groups? any other though for a glyph?

**Comment by lmihalkovic** [comment]
This is what it looks like for now (I need a better glyph than my crummy drawing code)

Default is no grouping
<img width="200" alt="screen shot 2016-02-24 at 4 48 18 pm" src="https://cloud.githubusercontent.com/assets/1318077/13291049/a0bb8252-db16-11e5-9c10-054014953fd1.png">

And then byYear or byTrack:
<img width="200" alt="screen shot 2016-02-24 at 4 45 20 pm" src="https://cloud.githubusercontent.com/assets/1318077/13291066/b4d23c9a-db16-11e5-8394-2b68dc731555.png">
<img width="200" alt="screen shot 2016-02-24 at 4 45 41 pm" src="https://cloud.githubusercontent.com/assets/1318077/13291067/b542bc0e-db16-11e5-9f07-6abe4673c0da.png">

**Comment by insidegui** [comment]
@lmihalkovic Put a placeholder image in `Images.xcassets`, I can find new icons later ;)
